### PR TITLE
Add WSGIScriptAliasesMatch support

### PR DESCRIPTION
**Pull request by doprdele**
I noticed that the PuppetLabs apache module has WSGIScriptAliases support but not WSGIScriptAliasesMatch support. i added this functionality as well as updated the tests. Let me know if I should make any changes. Thanks!

### CODE REVIEW

**Comment by jonnytpuppet** [comment]
Hi There

Thanks for your contribution!

It would be appreciated if you could update the README with this added functionality.
Please remember to squash your commits :)

Thanks!

**Comment by doprdele** [comment]
Hi,

Should I update the CHANGELOG as well?

Best,
Evan

**Comment by jonnytpuppet** [comment]
Sure :)

**Comment by doprdele** [comment]
all set!

**Comment by tphoney** [comment]
#1485 supersedes this

**Pull request closed without merging**
