### PR TITLE
ThreadLimit needs to be above MaxClients or it is ignored. https://bz…

### PR DESCRIPTION
**Pull request by mattkenn4545**
….apache.org/bugzilla/show_bug.cgi?id=46113

This should also be forwardported but we are currently stuck at 1.2

### CODE REVIEW

**Comment by igalic** [comment]
@mattkenn4545 does this apply only to mpm_worker? not event, or any others?

**Comment by HelenCampbell** [comment]
@mattkenn4545 Ping on this for @igalic 's question. Also can you have a look at the failing tests before this is further reviewed?

**Comment by bmjen** [comment]
The tests are failing lint.

~~~
manifests/mod/version.pp - WARNING: top-scope variable being used without an explicit namespace on line 3
manifests/params.pp - WARNING: double quoted string containing no variables on line 107
The command "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'" exited with 1.
~~~

**Comment by igalic** [comment]
+1 from @igalic

**Comment by bmjen** [comment]
@mattkenn4545 Can you reopen this PR against `master`? Or are you pinning to the 1.2.x branch on github right now? I don't think we'll be doing any new 1.2.x releases anymore.

**Comment by HelenCampbell** [comment]
@mattkenn4545 Ping for @bmjen 's question :)

**Comment by mentat** [comment]
Hi there, if you can re-open this against master we can probably help you merge this in. Thanks!

**Comment by tphoney** [comment]
closing due to the merging off #1351. Thanks for the work @mattkenn4545

**Pull request closed without merging**
