### PR TITLE
(MODULES-9014) Add SSLSessionTickets parameter

### PR DESCRIPTION
**Pull request by FredericLespez**
Add the boolean parameter ssl_sessiontickets to apache::mod::ssl
Use parameter ssl_sessiontickets in ssl.conf.erb
Add unit tests for parameter ssl_sessiontickets
Document the parameter ssl_sessiontickets

### CODE REVIEW

**Comment by FredericLespez** [comment]
Acceptance tests failed on Ubuntu 14.04 because the Apache version on this distribution is 2.4.10.
And SSLSessionTickets is only available since Apache 2.4.11 :-(
Since apache::version doesn't handle the detailed Apache version (but only 2.2 or 2.4), I  don't know how to handle this.
Any advice ?

**Comment by FredericLespez** [comment]
Patch rebased on current master.

**Comment by FredericLespez** [comment]
In case it wasn't clear:
I fix the acceptance tests by ignoring the SSLSessionTickets parameter on Ubuntu 14.04 (Since Ubuntu 14.04 ships with Apache 2.4.10 and SSLSessionTickets is available in Apache 2.4.11 or newer).

The pull request has been updated, rebased on current master and all checks are OK.

**Comment by sheenaajay** [comment]
@FredericLespez Thanks for your contribution.

**Comment by FredericLespez** [comment]
@sheenaajay Thanks !

**Comment by sheenaajay** [comment]
@FredericLespez looks like the same problem with Debian 8 platform also. Getting  a PR to add an exception to Debian and also updating the default value to false. Will get the PR up for review soon.

Acceptance tests failed on Ubuntu 14.04 because the Apache version on this distribution is 2.4.10.
And SSLSessionTickets is only available since Apache 2.4.11

**Comment by FredericLespez** [comment]
@sheenaajay Same problem indeed with Debian 8 (it ships Apache 2.4.10).
Setting the default value to false won't help: Apache will complain that this setting doesn't exists.
Would it help you if I provide a new PR for handle Debian 8 ?

**Comment by sheenaajay** [comment]
@FredericLespez cool. Thats great. Also, could you update the default value for the new parameter to false and update the unit tests. Thanks alot for all the contribution.

**Comment by FredericLespez** [comment]
@sheenaajay Sure. I will open a new pull request shortly.

**Pull request merged**
