### PR TITLE
Drop support for Debian < 9

### PR DESCRIPTION
**Pull request by ekohl**
This is a draft PR to push my local code. It includes https://github.com/puppetlabs/puppetlabs-apache/pull/2110. The idea is to keep the codebase smaller. Maybe this is too soon, but I'd like some feedback.

Alternatives are to drop Debian < 8 and Ubuntu < 16.04.

### CODE REVIEW

**Comment by sanfrancrisko** [comment]
Let me start the conversation internally about dropping support for Debian < 9 and Ubuntu < 16.04. Now that Puppet 5 is officially EOL'd, those platforms fall under that umbrella too.

Given Debian 8 is still officially supported on Puppet 6, I'm not sure we can make any moves to deprecate any of that functionality.

**Comment by ekohl** [comment]
Let me know if I should submit the Ubuntu 10.04 removal separate. That feels like a safe one to remove at this point. I can also take a look at removing Debian < 8.

Another thing to note is that Ubuntu 16.04 standard support will go EOL in April.

**Comment by sanfrancrisko** [comment]
Thanks @ekohl - yeah, if you could, putting up a separate PR for the removal of Ubuntu 10.04 would be good. We can get that in fairly quickly.

**Comment by ekohl** [comment]
https://github.com/puppetlabs/puppetlabs-apache/pull/2129 is that. https://github.com/puppetlabs/puppetlabs-apache/pull/2110 should also be merged before this PR can be moved out of draft.

**Comment by ekohl** [comment]
I did split the commits a bit. I'd be interested to know what level of support is desired. The commit < 8 and < 16.04 felt safe, but it looks like 14.04 still has LTS support until 2022.

Would you mind taking a look at the commits and stating what level of support is desired?

**Comment by david22swan** [comment]
@ekohl Apologies but it looks like we're set to keep Debian 8 support for a while longer as it was included in the last LTS agent release.
The Ubuntu changes on the other hand look good and I would be quite happy to merge them.

**Comment by ekohl** [comment]
I've rebased this and submitted https://github.com/puppetlabs/puppetlabs-apache/pull/2188 to at least get the preparation out. After that's merged, I can submit the first commit as a PR. It should be safe to drop Debian < 8 and 14.04 at least.

**Comment by ekohl** [comment]
I've submitted https://github.com/puppetlabs/puppetlabs-apache/pull/2189 as a first PR.

**Comment by ekohl** [comment]
Rebased to resolve conflicts.

**Review by bastelfreak — APPROVED** [review]

**Comment by david22swan** [comment]
@ekohl Apologies but when I state yesterday that we could get this merged I was on my way out and did not recognize that this PR included the dropping of Ub16.04 which is still currently supported by the puppet agent and as such must continue to be supported by our modules.
I am attempting to find some clarification on when Ub 16.04 will be dropped and am hoping to get a response by the end of today.
Once again sorry that we can't get this PR merged as it is now.

**Comment by ekohl** [comment]
I dropped the Ubuntu 16.04 removal commit and also updated the tests to default to Debian 11 instead of 8. Also cleaned up some other testing code.

**Review by bastelfreak — APPROVED** [review]

**Comment by david22swan** [comment]
@ekohl Look's like we're still getting some spec test failures

**Comment by bastelfreak** [comment]
The issue for the missing gems: https://tickets.puppetlabs.com/browse/MODULES-11161 (plus all linked issues)

**Comment by david22swan** [comment]
@ekohl Took a quick look at the spec test failures and did some fixes on them, a few package names had been changed between Deb 8 and 11 and that was throwing the failures.
Currently looking at the last failure, just need to give it a proper look over but it shouldn't be too hard to fix.
Sorry for pushing up without asking but figured you'd want this done quick.

**Comment by ekohl** [comment]
I pushed another one that was still missing. I get the impression that the whole proxy_html mod was dropped in Debian 9 because I can't find the package. Or is it part of another package?

**Comment by david22swan** [comment]
@ekohl From what I can find the `libapache2-mod-proxy-html` package was a transitional one that was only present within 8 and removed in 9 and up

**Review by david22swan — APPROVED** [review]
Everything LGTM so gonna go ahead and merge :)
Apologies for the wait on this

**Comment by david22swan** [comment]
Just updated the title of the pr so it's clear when displayed within the changelog

**Comment by ekohl** [comment]
This also drops Ubuntu < 16.04 (14.04 was in metadata). Shouldn't that also be in the message?

**Comment by david22swan** [comment]
@ekohl Did you not drop the 16.04 removal from it?

**Comment by david22swan** [comment]
Ah, I see where I went wrong sorry. Yeh this is all good

**Pull request merged**
