### PR TITLE
[#puppethack] Added documentation for ForceType directive (MODULES-2152)

### PR DESCRIPTION
**Pull request by bmurtagh**

### CODE REVIEW

**Comment by igalic** [comment]
thank you for the patch, @bmurtagh 

two issues: it needs a [rebase](http://git-scm.com/book/en/Git-Branching-Rebasing)
and, if you want, for extra internet points, you can change your committer author to the one matching your GitHub profile (or add the email in this commit to your github profile)

**Comment by bmurtagh** [comment]
@igalic looking better now?

**Comment by igalic** [comment]
let's make @bmurtagh a git pro!

*****
```
# fork puppetlabs-apache
# clone your fork:

% git clone git@github.com:bmurtagh/puppetlabs-apache
% cd puppetlabs-apache
# add puppetlabs repo as another `remote` called `upstream`
# (the default `remote` is usually called `origin`
# checkout a new branch and hack away
% git checkout -b fix/MODULES-2152
# (you're done with that bit ;)
# make sure you're up-to-date with upstream!
% git remote update # updates all remotes
% git rebase upstream/master # rebase against upstream's master
```


that's rebasing… (git should be easier)

if you wanna squash things, you can use

```
% git rebase -i HEAD~3 # 3 is the number of commits you wanna… deal with…
# follow the instructions in your editor
```

which usually means changing something like this:

```
pick 1549db9 Add Solaris support to MySQL module
pick 545abcf [#puppethack] use of mysql::db without mysql::server
pick 98bbc62 autorequire mysql::server in types
````

into something like this:

```
pick 1549db9 Add Solaris support to MySQL module
s 545abcf [#puppethack] use of mysql::db without mysql::server
s 98bbc62 autorequire mysql::server in types
```

**Comment by igalic** [comment]
*boom* thanks @bmurtagh!

**Pull request merged**
