### PR TITLE
Add MellonSetEnv support

### LINKED ISSUE #2416: MellonSetEnv
## Use Case
Currently we have forked this module to include MellonSetEnv since it's not done natively within this module

## Describe the Solution You Would Like
I would like MellonSetEnv to be added so that we can upgrade the module with ease without having to keep merging in MellonSetEnv

## Additional Context
We currently have a forked version where we have the following added to https://github.com/puppetlabs/puppetlabs-apache/blob/main/templates/vhost/_directories.erb#L431

As far as I know this isn't something custom to us and that other users may want to use this feature.

```
      <%- if directory['mellon_set_env'] -%>
        <%- directory['mellon_set_env'].each do |key, value| -%>
    MellonSetEnv "<%= key %>" "<%= value %>"
        <%- end -%>
      <%- end -%>
```

Thanks
Ian

### PR DESCRIPTION
**Pull request by ic248**
Add MellonSetEnv support, will prepend MELLON_ to the environment variable name

Fixes #2416

### CODE REVIEW

**Comment by ic248** [comment]
This is for issue #2423

**Comment by jordanbreen28** [comment]
@ic248 thanks for this submission!
Could you add a description to this PR?

**Review by smortex — APPROVED** [review]

**Comment by ic248** [comment]
Anything else required from me to get this merged?

**Comment by bastelfreak** [comment]
@ic248 can you please rebase and add a unit test?

**Comment by ic248** [comment]
@bastelfreak I've rebased, not sure where to start for a unit test, as far as I can see none of the mod_auth_mellon directives currently have any form of tests. If you could push me in the right direction I could create something (not created unit tests before).

Thanks
Ian

**Comment by smortex** [comment]
I think you can add a new directory in `spec/defines/vhost_spec.rb` near line 303 with a somewhat complete `mellon_*` configuration (the test context is intended to set all parameters and check them all), and adjust near line 723 to add the corresponding checks.

We have some pointers to run unit tests here:
https://voxpupuli.org/docs/how_to_run_tests/

**Comment by ic248** [comment]
rebased again and added unit tests for mellon_*

**Comment by smortex** [comment]
Thanks!  CI failure is just anoyance, I suggest adding a "magic comment" before line 631:

```
# rubocop:disable RSpec/ExampleLength
```

and the corresponding magic comment on line 750:

```
# rubocop:enable RSpec/ExampleLength
```

That should fix it!

**Comment by ic248** [comment]
Thanks @smortex I've added your suggestions, you've all been really helpful since I'm new to a lot of these CI and unit tests

**Review by smortex — APPROVED** [review]
LGTM!

**Comment by ic248** [comment]
Does anyone else need to review this before it can be merged in?

**Comment by ic248** [comment]
Looks like things failed due to Puppet forge being down for maintenance

**Comment by malikparvez** [comment]
> @malikparvez looks like Puppet forge is back online, should be good to rerun checks

yes @ic248 it is up now and ci is successful...

**Comment by malikparvez** [comment]
thanks for your contribution @ic248

**Pull request merged**
