### PR TITLE
MODULES-9083: remove double quotes to allow flags in SSLCARevocationCheck

### PR DESCRIPTION
**Pull request by jnguiot**
This is a solution to solve the bug I have submitted ([MODULES-9083](https://tickets.puppetlabs.com/browse/MODULES-9083)).
I hope it can help.
Best Regards

### CODE REVIEW

**Comment by sheenaajay** [comment]
Thanks for submitting the PR @jnguiot .Reviewing the changes and executing the adhoc jobs.

**Comment by sheenaajay** [comment]
Thanks a lot for your contribution @jnguiot  .Some of the ad-hoc jobs are failing. Could you please rebase your changes with the master. Since there are changes on metadata.json to use the latest version of dependent modules.

**Comment by sheenaajay** [comment]
Thanks a lot for your contribution @jnguiot .Could you please resolve the conflict. Thank you.

**Comment by jnguiot** [comment]
Hi @sheenaajay,
I made a rebase to add my modification onto master. You can find it in this PR1946: https://github.com/puppetlabs/puppetlabs-apache/pull/1946 . 
Thus, this PR can be cancelled and closed.

**Pull request closed without merging**
