### PR TITLE
Configurability of Collaborative Detection Severity Levels for OWASP Core Rule Set

### PR DESCRIPTION
**Pull request by FlatKey**

### CODE REVIEW

**Comment by jonnytpuppet** [comment]
@FlatKey it would be appreciated if you could rebase this against current master as changes have gone in that should fix the failing unit tests (assuming nothing in this PR breaks them).

Thanks

**Comment by FlatKey** [comment]
@jonnytpuppet rebased.

**Comment by igalic** [comment]
gosh, after merging #1403 , this needs a rebase again, sorry @FlatKey

**Comment by FlatKey** [comment]
@igalic no problem, rebased :o)

**Comment by bmjen** [comment]
@FlatKey sorry, can you rebase this again?

**Comment by FlatKey** [comment]
@bmjen no problem, rebased again.

**Comment by HelenCampbell** [comment]
@FlatKey Merged! Apologies about all the rebases, thanks for all your patience!

**Pull request merged**
