### PR TITLE
Resolve easy puppet-lint notices

### PR DESCRIPTION
**Pull request by jcpunk**
This resolves the majority of puppet-lint notices.

### CODE REVIEW

**Comment by igalic** [comment]
the test failures are facter related and have nothing to do with your change

**Comment by sanfrancrisko** [comment]
@jcpunk This looks like it is a similar issue to what @adrianiurca mentioned [here](https://github.com/puppetlabs/puppetlabs-firewall/pull/943#issuecomment-693520842)

**Comment by jcpunk** [comment]
I've taken a stab at getting the spec tests to set the right facts for the modern layout.

I'll confess I could use a hand with `spec_helper_acceptance_local.rb` among others.

**Comment by jcpunk** [comment]
I just looked at the size of that patch....

New plan, I'm going to just post a patch for the non-fact fixes...

**Comment by adrianiurca** [comment]
Hi @jcpunk, thank you for your contribution!

**Review by adrianiurca — APPROVED** [review]

**Pull request merged**
