### PR TITLE
Additional commands to detect Apache version and regexp check

### PR DESCRIPTION
**Pull request by denzery**
Add additional commands to detect Apache version and make sure the regular expression actually matched something. On some Linux systems, the current fact shows the following error:

```
Error: Facter: error while resolving custom fact "apache_version": undefined method `[]' for nil:NilClass
```

### CODE REVIEW

**Comment by david22swan** [comment]
@denzery Your change is currently failing against the unit tests. If you could take a look and get them working we could see about getting this merged.

**Comment by david22swan** [comment]
@denzery Is there any movement on this pr?

**Comment by lionce** [comment]
Hello @denzery ,

How is it going with this PR? It looks like the unit tests are failing and a spec file has conflicts. In order to merge this PR please fix the issues and rebase it with the latest code version. Please let us know if you need any help!

**Comment by denzery** [comment]
@lionce sorry for taking so long. I have merged and adjusted the changes in the spec file now.

**Comment by lionce** [comment]
Hello @denzery ,

Thanks for your contribution. It looks good to me! Well done! :)

Cheers!

**Pull request merged**
