### PR TITLE
default server_tokens to prod - more secure default

### PR DESCRIPTION
**Pull request by juju4**
Goal: provide a sane & secure default configuration for modern webserver

This is a minor change to have more secure default for apache tokens.
Most people will not update/forget it for production.

### CODE REVIEW

**Comment by hunner** [comment]
Seems reasonable. The readme would need updating https://github.com/puppetlabs/puppetlabs-apache#server_tokens

Also, this will probably not make it in for a bit, since it's arguably a backwards-incompatible change, not a bugfix.

**Comment by david22swan** [comment]
@juju4 Apologies for the long wait, I am currently looking to merge your pr, however I would need it to be rebased first in order to effectively test it's changes on our adhoc pipeline, due to the updates made to the module since it's creation.

**Comment by juju4** [comment]
done. Thanks

**Comment by pmcmaw** [comment]
@juju4 thank you for taking the time to contribute to this supported module.
Your PR has now been merged.

Many Thanks
The Modules Team

**Pull request merged**
