### PR TITLE
add support for SSLProxyProtocol directive

### PR DESCRIPTION
**Pull request by saimonn**

### CODE REVIEW

**Comment by hunner** [comment]
Looks good! Could you add docs for the new parameter to the readme as well? Thanks!

**Comment by saimonn** [comment]
Just added doc in README.md
@hunner or @igalic, do you want me to squash the two commits?

**Comment by igalic** [comment]
nah, it's fine, but i'm just thinking that it doesn't have tests :D

**Comment by saimonn** [comment]
@igalic  and here comes the tests

**Comment by igalic** [comment]
thanks @saimonn!

**Pull request merged**
