### PR TITLE
Use concat 1.2.x

### PR DESCRIPTION
**Pull request by mhaskel**

### CODE REVIEW

**Comment by igalic** [comment]
:(
when can we switch?

**Comment by Jeoffrey54** [comment]
Same issue for me :(.

**Comment by mhaskel** [comment]
switching to concat 2.x is a backwards-incompatible change. I'm guessing at some point we'll have releases of everything dependent on the newer concat, but as that hasn't been released (and hasn't fully stabilized yet) we need to pin our dependencies so things don't explode.

**Comment by domcleal** [comment]
It seems that 2.x ended up being pretty much compatible (which makes me very happy), so I've opened #1126 to relax the deps and fix deprecations.

**Pull request merged**
