### PR TITLE
Add RewriteMap support

### PR DESCRIPTION
**Pull request by soerenbe**
Here is the patch to support apache RewriteMap.

Since this is my first contribution/pull request every feedback is very wellcome.

### CODE REVIEW

**Comment by soerenbe** [comment]
Associated ticket: https://tickets.puppetlabs.com/browse/MODULES-1689

**Comment by igalic** [comment]
@soerenbe thank you very much for this contribution.
i *think* we have spec thests for rewrite_stuff. would you mind adding rewrite_map to those tests as well?

**Comment by soerenbe** [comment]
@igalic I will try. Last time i tried it, i didn't get all the spec tests to run on my Ubuntu 14.04 box because of some fancy ruby error. So I gave up after a hour. I will trie it tomorrow.

**Comment by soerenbe** [comment]
@igalic Ok - I got it.
It took me hours to get vagrant running, but finally I got it. I added a the test and it passes.

**Comment by mhaskel** [comment]
Hi @soerenbe, this looks good, thanks! Could you please squash this down to a single commit, then we should be good to merge!

**Comment by igalic** [comment]
@soerenbe ping

**Comment by soerenbe** [comment]
@igalic : Done. 
When you need something else drop me a line.

I just realized that there is a similar (old?) pull request here: https://github.com/puppetlabs/puppetlabs-apache/pull/900

**Comment by igalic** [comment]
@soerenbe thanks you.

re #900: sometimes pull requests are forgotten, either by us, or by their authors :(

**Pull request merged**
