### PR TITLE
MODULES-5871 Add X-Frame-Options to httpd.conf

### PR DESCRIPTION
**Pull request by sudodevnull**
Required for CIS Apache HTTP Server 2.4 Benchmark v1.3.0

1.5.14 Restrict Browser Frame Options (Scored)
Profile Applicability:
• Level 2
Description:
The Header directive allows server HTTP response headers to be added, replaced or
merged. We will use the directive to add an server HTTP response header to tell browsers
to restrict all of the web pages from being framed by other web sites.
Rationale:
Using iframes and regular web frames to embed malicious content along with expected
web content has been a favored attack vector for attacking web clients for a long time. This
can happen when the attacker lures the victim to a malicious web site, which using frames
to include the expected content from the legitimate site. The attack can also be performed
via XSS (either reflected, DOM or stored XSS) to add the malicious content to the legitimate
web site.
To combat this vector, an HTTP Response header, X-Frame-Options, has been introduced
that allows a server to specify whether a web page may be loaded in any frame (DENY) or
those frames that share the pages origin (SAMEORIGIN).
Audit:
Perform the following steps to determine if the recommended state is implemented:
1. Ensure a Header directive for X-Frame-Options is present in the Apache
configuration and has the condition always, an action of append and a value of
SAMEORIGIN or DENY, as shown below.:
# grep -i X-Frame-Options $APACHE_PREFIX/conf/httpd.conf
Header always append X-Frame-Options SAMEORIGIN
Remediation:
Perform the following to implement the recommended state:
1. Add or modify the Header directive for the X-Frames-Options header in the Apache
configuration to have the condition always, an action of append and a value of
SAMEORIGIN or DENY, as shown below.
Header always append X-Frame-Options SAMEORIGIN
86 | P a g e
Default Value:
The X-Frame-Options HTTP response header is not generated by default.
References:
1. http://httpd.apache.org/docs/2.4/mod/mod_headers.html#header
2. https://developer.mozilla.org/en/The_X-FRAME-OPTIONS_response_header/
3. http://blogs.msdn.com/b/ie/archive/2009/01/27/ie8-security-part-viiclickjacking-
defenses.aspx

### CODE REVIEW

**Comment by ekohl** [comment]
It looks like this is missing a parameter somewhere, but more concrete this feels too specific. Why this header? If you want to set global headers I think a hash like in vhosts (https://github.com/puppetlabs/puppetlabs-apache/blob/f0c33c248a13f51fa54f742fe7c664a8e031eb82/manifests/vhost.pp#L102) is more appropriate. That way ssers can also set headers like ```X-Content-Type-Options``` or ```X-XSS-Protection``` globally.

**Comment by sudodevnull** [comment]
Ekohl,
I have the parameter set here [c0ad8bd](https://github.com/puppetlabs/puppetlabs-apache/pull/1717/commits/c0ad8bd16901a51f3dd8d75efe860774bf276c7b)

So you are saying to set $headers = 'always append X-Frame-Options SAMEORIGIN'  ?
or would it be $headers = 'Header always append X-Frame-Options SAMEORIGIN' ?

Sorry, I am new to apache and am just trying to ensure my apache deployments meet CIS compliance standards.  Also, there is not much documentation in the [readme](https://github.com/sudodevnull/puppetlabs-apache#headers).

**Comment by ekohl** [comment]
Maybe ```params.pp``` should be called ```defaults.pp``` but this is now an established pattern in puppet module development. Typically you also add it to ```init.pp``` so the user has a place to actually override the default value.

You could have a look at https://github.com/puppetlabs/puppetlabs-apache#headers because the module already allows to set headers for a single vhost. If you do that for every vhost, then you can already make your server CIS compliant. https://github.com/puppetlabs/puppetlabs-apache/blob/master/templates/vhost/_header.erb is the used template so that means you can set it to ```'always append X-Frame-Options SAMEORIGIN'```.

**Comment by sudodevnull** [comment]
https://github.com/puppetlabs/puppetlabs-apache/blob/master/manifests/mod/headers.pp
Does this even work?  I assign headers => 'always append X-Frame-Options SAMEORIGIN', and now I am getting a dependency cycle between a sudo class that manages our sudoers file and the apache::mod::headers manifest.  See the below diagraph:

# cat /opt/puppetlabs/puppet/cache/state/graphs/cycles.dot
digraph Resource_Cycles {
  label = "Resource Cycles"
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Exec[mkdir /etc/httpd/conf.modules.d]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Linuxauth]" -> "Class[Linuxauth]" -> "Stage[postfeatures]"
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Exec[mkdir /etc/httpd/conf.modules.d]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Sudo]" -> "Anchor[sudo::begin]"
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Package[httpd]" -> "Exec[mkdir /etc/httpd/conf.modules.d]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Sudo]" -> "Anchor[sudo::begin]"
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Package[httpd]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Linuxauth]" -> "Class[Linuxauth]" -> "Stage[postfeatures]"
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Package[httpd]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Sudo::Configs]" -> "Class[Sudo::Configs]" -> "Stage[postfeatures]"
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Package[httpd]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Sudo::Params]" -> "Class[Sudo::Params]" -> "Stage[postfeatures]"
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Package[httpd]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Sudo]" -> "Anchor[sudo::begin]"
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Package[httpd]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Sudo]" -> "Anchor[sudo::end]" -> "Class[Sudo]"
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Package[httpd]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Sudo]" -> "File[/etc/sudoers.d/]" -> "Class[Sudo]"
"Anchor[sudo::begin]" -> "Class[Sudo]" -> "Stage[postfeatures]" -> "Stage[hieraclasses]" -> "Class[Apache]" -> "Package[httpd]" -> "File[headers.load]" -> "Apache::Mod[headers]" -> "Class[Apache::Mod::Headers]" -> "Stage[main]" -> "Stage[postfeatures]" -> "Class[Sudo]" -> "File[/etc/sudoers]" -> "Class[Sudo]"
}

**Comment by ekohl** [comment]
That's only the class which doesn't set any headers. It's the ```$headers``` parameter on ```apache::vhost``` I was talking about.

**Comment by sudodevnull** [comment]
OK, do you know why this requires running in the main stage or any way to disable this?  I am experiencing a dependency cycle when trying to pass the header. 

Error: Failed to apply catalog: Found 1 dependency cycle:
(Anchor[sudo::begin] => Class[Sudo] => Stage[postfeatures] => Stage[hieraclasses] => Class[Apache] => Package[httpd] => File[headers.load] => Apache::Mod[headers] => Class[Apache::Mod::Headers] => Stage[main] => Stage[postfeatures] => Class[Sudo] => Anchor[sudo::begin])

**Comment by ekohl** [comment]
I've never used stages and I wonder why your sudo class is chained to it.

**Comment by sudodevnull** [comment]
The sudo is not the issue, I believe it's calling main which then calls sudo. I'm not sure why the module calls main.

**Comment by ekohl** [comment]
Like I said, I've never used stages but I don't see any reference to ```main``` or even ```stage``` in this module.

**Comment by david22swan** [comment]
@sudodevnull please alter the docs to mirror your changes and ensure that you have testing in place to account for them.

**Comment by david22swan** [comment]
Closing and reopening PR to solve bundler issue

**Comment by david22swan** [comment]
@sudodevnull Is there any movement on the addition of test coverage?

**Comment by hunner** [comment]
@sudodevnull Do you have a `Package <| |> -> Stage['main']` anywhere that could be pinning the httpd package (and thus much of the apache module) into the main stage?

But anyway, the `apache::vhost::headers` parameter is used to set any headers on a vhost and no special hard-coded header parameters are needed. Just trying to keep this module as general as possible :).

**Pull request closed without merging**
