### PR TITLE
Clean up includes and templates in vhost.pp

### PR DESCRIPTION
**Pull request by ekohl**
This localizes the includes in vhost.pp which removes some duplicated logic. Sometimes the logic was also slightly different. This keeps it consistent.

It also only includes modules if ensure is set to present. This allows users to toggle the ensure easily and only having the minimal amount of modules present.

### CODE REVIEW

**Comment by ekohl** [comment]
Acceptance is still running, but this looks like it'll be green.

**Review by david22swan — APPROVED** [review]
LGTM

**Comment by david22swan** [comment]
And that's another one in, sorry for the wait on merge, was off yesterday

**Comment by ekohl** [comment]
No worries, thanks for the merge.

**Pull request merged**
