### PR TITLE
pdksync - Update gha templates

### PR DESCRIPTION
**Pull request by DavidS**
Update gha templates
pdk version: `1.19.0.pre (47)`

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Btw, recently I saw https://github.com/FragileTech/bump-version and that uses pure YAML as an action. It's on my agenda to see if this can be used to avoid syncing these complex workflows to every repo.

**Comment by DavidS** [comment]
> Btw, recently I saw https://github.com/FragileTech/bump-version and that uses pure YAML as an action. It's on my agenda to see if this can be used to avoid syncing these complex workflows to every repo.

Yeah this is pretty nasty. One of the changes here is to flip over small third-party actions to something we can control so

**Comment by DavidS** [comment]
restarted travis with repo checksum errors

**Comment by DavidS** [comment]
> Btw, recently I saw https://github.com/FragileTech/bump-version and that uses pure YAML as an action. It's on my agenda to see if this can be used to avoid syncing these complex workflows to every repo.

No argument here. Github has dropped the ball on making Actions good for larger organisations. Let's be real, we're only using them because Puppet already pays for it. I've looked at gitlab a couple of times, and a gitlab instance would provide some significant benefits to our CI implementation.

**Review by sanfrancrisko — APPROVED** [review]

**Pull request merged**
