### PR TITLE
[FM-6958] Removal of unsupported OS from apache

### PR DESCRIPTION
**Pull request by david22swan**

### CODE REVIEW

**Comment by david22swan** [comment]
related pr: https://github.com/puppetlabs/ci-job-configs/pull/4542

**Comment by tphoney** [comment]
@david22swan RE the failure, read the tests what are we testing for ?
Are there bigger ramifications inside manifests/version.pp
There are a number of spots where it still references debian 6

**Comment by david22swan** [comment]
The part's that still reference 6 are ones that I've reverted due to them breaking once changed. Had planned to make a separate ticket to fully update all the references to allow me to finish removing support from all the modules first.

**Comment by ekohl** [comment]
Any reason to remove SL 5 but keep CentOS/RHEL 5 which are both EOL?

**Comment by davinhanlon** [comment]
Hi @ekohl - thanks for raising this. RHEL 5 has extended life cycle support until 2020: https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates. Thanks for pointing out CentOS 5 though, we should remove that (https://wiki.centos.org/FAQ/General#head-fe8a0be91ee3e7dea812e8694491e1dde5b75e6d).

**Pull request merged**
