### PR TITLE
support Ubuntu xenial (16.04)

### PR DESCRIPTION
**Pull request by mmoll**
cherry-pick of c376776, a 1.8.2 release with this would be nice.

### CODE REVIEW

**Comment by tphoney** [comment]
@mmoll hi, thanks for the PR. We will soon be looking at 16.04 here at puppet. There is oneslight issue, could you create this PR against master and not the 1.8.x branch.

**Comment by mmoll** [comment]
@tphoney this already is in master, but not in 1.8.x.

**Comment by tphoney** [comment]
@mmoll if it is in master, we will move this to the 1.8.x branch when we do the next apache release. It makes this PR a little redundant. I will push for an apache release soon. Or if you want to create a ticket here https://tickets.puppetlabs.com/secure/CreateIssue!default.jspa that will help too. 

I will now close this PR. Thanks for the work you put in.

**Comment by mmoll** [comment]
@tphoney I see thanks. I created https://tickets.puppetlabs.com/browse/MODULES-3260

**Comment by tphoney** [comment]
Thanks @mmoll it looks like there will be a release in the next couple of weeks.

**Pull request closed without merging**
