### PR TITLE
apache::vhost filter support

### PR DESCRIPTION
**Pull request by BIAndrews**
This adds support for specifying filters in an apache::vhost.

### CODE REVIEW

**Comment by jonnytpuppet** [comment]
Thank for your contribution. I'd love to see this merged. Please add a test case for this. Either a unit test or a spec test will do. Thanks!

**Comment by BIAndrews** [comment]
I'm sorry I'm very new to this. Should I close this PR and make a new one with the added unit test?

**Comment by bryanandrews** [comment]
That's reall cool, it just worked

**Comment by jonnytpuppet** [comment]
Thanks, but unfortunately, the 'tests' directory are not actually tests. That folder should be renamed to 'examples' by a new PR (ignore this for now). All unit and spec tests are in the spec directory.

Thanks!

**Comment by bryanandrews** [comment]
Is there anything else you'd like added?

**Pull request merged**
