### PR TITLE
(MODULES-2440) Allow installing additional php-related packages

### PR DESCRIPTION
**Pull request by yakatz**

### CODE REVIEW

**Comment by igalic** [comment]
@yakatz frankly, i think this is the wrong place to do that.
you should be using a php module to manage those.

**Comment by yakatz** [comment]
I just made a patch for the open ticket because it overlaps with our needs.

**Comment by abednarik** [comment]
See this PR https://github.com/puppetlabs/puppetlabs-apache/pull/1247

**Comment by bmjen** [comment]
@yakatz Thanks for the contribution, but I'm going to have to agree with @igalic. These packages are better suited to be managed by a php module and falls outside of the scope of this Apache module.

**Pull request closed without merging**
