### PR TITLE
Allow package names to be specified for mod_proxy, mod_ldap, and mod_authnz_ldap

### PR DESCRIPTION
**Pull request by MG2R**
Simple change to allow users to change the package name on the aforementioned mods. This is based on the code for mod::ssl, which already had this feature.

I'm not (very) experienced in the subject of spec tests and could use some help if those need to be improved as well. The code works as expected in my setup.

### CODE REVIEW

**Comment by DavidS** [comment]
This is a quite trivial change, so additional spec coverage is not really required. What you should do, though, is adding the params to the README, so people can find them, and do not need to guess.

**Comment by MG2R** [comment]
Updated the README. Sorry for the delay.

**Comment by tphoney** [comment]
With the recent merges, you will need to rebase this. Many apologies.

**Comment by MG2R** [comment]
No problem. Learned something new :)

**Pull request merged**
