### PR TITLE
Add request headers on a per directory basis.

### PR DESCRIPTION
**Pull request by grim8634**
Add request headers on a per directory basis, rather than just globally for the vhost.

### CODE REVIEW

**Comment by igalic** [comment]
@grim8634 could you plz document this?
Also: do we need to include mod_header for this?

**Comment by grim8634** [comment]
@igalic Updated docs thanks.
Yes, it requires mod_headers. There's no automatic checking it's loaded anywhere is there?

**Comment by igalic** [comment]
@grim8634 here's how we do it at vhost level: https://github.com/puppetlabs/puppetlabs-apache/blob/master/manifests/vhost.pp#L440-L445

**Comment by DavidS** [comment]
Unless anybody has a better idea, I'd suggest using a inline_template and some ruby to check whether $directories has request headers and add a check like @igalic  suggested to include the mod_headers conditionally.

**Comment by igalic** [comment]
@DavidS can you imagine what kind of face i'm making rn?

**Comment by DavidS** [comment]
@igalic probably something involving rainbows and buckets?

**Comment by jonnytpuppet** [comment]
@grim8634 I think your Readme is wrong. The property is called "headers" but in the template logic it's "request_headers". Am i missing something here?

Also, your tests need to pass before we can merge this.

Thanks!

**Comment by bmjen** [comment]
Hi @grim8634 has there been any progress on addressing the feedback for this PR?

**Comment by tphoney** [comment]
Hi @grim8634 , thanks for the work you have put into this pull request. However due to inactivity and and the comments not being addressed this pull request is being closed. If you want to re-submit this PR with the necessary changes, we will gladly look at the new pull request.

**Pull request closed without merging**
