### PR TITLE
Allow RewriteInherit with empty rewrites

### PR DESCRIPTION
**Pull request by martin-koerner**
There are cases where you want to exclusively inherit RewriteRules from e.g. global scope without specifying vHost-specific rewrites - which is now allowed again.

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Could you add a test case for this?

**Comment by martin-koerner** [comment]
> Could you add a test case for this?

Sure, I updated the existing one for empty rewrites with rewrite_inherit = false and added a second one - hope that's sufficient:
```
        empty rewrites
          is expected not to contain Concat::Fragment[rspec.example.com-rewrite]
        empty rewrites_with_rewrite_inherit
          is expected to contain Concat::Fragment[rspec.example.com-rewrite] with content =~ /^\s+RewriteOptions Inherit$/
```

**Review by david22swan — APPROVED** [review]
LGTM

**Comment by david22swan** [comment]
@martin-koerner This change looks good to me and the test coverage seems sufficient. Thanks for putting in the work :)

**Pull request merged**
