### PR TITLE
Fix mod_authz_ldap to work on RHEL7 and mod_ldap

### PR DESCRIPTION
**Pull request by simonoded**
Hi I fixed the load.erb to have condition on the mod_ldap for RedHat 7 and apache 2.4

### CODE REVIEW

**Comment by bmjen** [comment]
I can't seem to find any information about mod_authnz_ldap behaving differently on RHEL7...

@igalic can you provide any insight?

**Comment by igalic** [comment]
i'm sorry, but i really don't know anything about RHEL :(

**Comment by simonoded** [comment]
Hi I will send the logs on Wednesday.
Regards

Oded Simon

**Comment by simonoded** [comment]
The OS:
# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.1 (Maipo)
# rpm -qa |grep http
httpd-2.4.6-31.el7_1.1.x86_64
httpd-tools-2.4.6-31.el7_1.1.x86_64
# rpm -qa |grep mod_ldap
mod_ldap-2.4.6-31.el7_1.1.x86_64

The module.pp:
 class { 'apache': }
  class { 'apache::mod::ssl': }
  apache::mod { 'authnz_ldap': }
  class { '::apache::mod::php': }
  apache::vhost { 'nagios-ssl':
    servername  => "nagios.${dns_domain}",
    docroot     => '/usr/share/nagios',
    port        => '443',
    ssl         => true,
    ssl_cert    => "/etc/pki/tls/certs/star.${dns_domain}.crt",
    ssl_chain   => "/etc/pki/tls/certs/ca_${dns_domain}.crt",
    ssl_key     => "/etc/pki/tls/private/star_${dns_domain}.key",
    aliases     => [
      { scriptalias => '/cgi-bin/',
        path        => '/usr/lib64/nagios/cgi/',
      },
    ],
    directories => [
      { path            => '/usr/lib64/nagios/cgi',
        custom_fragment => "
          SSLRequireSSL
          Options ExecCGI
          AllowOverride None
          Order allow,deny
          Allow from all
        "
      },
      { path            => '/usr/share/nagios',
        custom_fragment => "
          SSLRequireSSL
          Options ExecCGI
          AllowOverride None
          Order allow,deny
          Allow from all
        "
      },
    ],
  }
  apache::vhost { 'nagios-non-ssl':
    servername      => "nagios.${dns_domain}",
    docroot         => '/usr/share/httpd/error',
    port            => '80',
    redirect_status => 'permanent',
    redirect_dest   => "https://nagios.${dns_domain}/",
  }

authnz_ldap.load file:
LoadModule authnz_ldap_module modules/mod_authnz_ldap.so
LoadModule ldap_module modules/mod_ldap.so


No error in the log
# systemctl stop httpd.service
# systemctl start httpd.service
# systemctl status httpd.service
httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled)
   Active: active (running) since Thu 2015-09-17 14:40:44 AEST; 3s ago
  Process: 12114 ExecStop=/bin/kill -WINCH ${MAINPID} (code=exited,
status=0/SUCCESS)
  Process: 29107 ExecReload=/usr/sbin/httpd $OPTIONS -k graceful
(code=exited, status=0/SUCCESS)
 Main PID: 12121 (httpd)
   Status: "Processing requests..."
   CGroup: /system.slice/httpd.service
           ├─12121 /usr/sbin/httpd -DFOREGROUND
           ├─12122 /usr/sbin/httpd -DFOREGROUND
           ├─12123 /usr/sbin/httpd -DFOREGROUND
           ├─12124 /usr/sbin/httpd -DFOREGROUND
           ├─12125 /usr/sbin/httpd -DFOREGROUND
           ├─12126 /usr/sbin/httpd -DFOREGROUND
           ├─12127 /usr/sbin/httpd -DFOREGROUND
           ├─12128 /usr/sbin/httpd -DFOREGROUND
           └─12129 /usr/sbin/httpd -DFOREGROUND

with authnz_ldap.load file:
LoadModule authnz_ldap_module modules/mod_authnz_ldap.so
systemctl stop httpd.service
# systemctl start httpd.service
Job for httpd.service failed. See 'systemctl status httpd.service' and
'journalctl -xn' for details.

/var/log/httpd/error_log:
[Thu Sep 17 14:42:17.159630 2015] [mpm_prefork:notice] [pid 12121] AH00170:
caught SIGWINCH, shutting down gracefully
[Thu Sep 17 14:42:22.342978 2015] [authnz_ldap:error] [pid 12266] AH01749:
Module mod_ldap missing. Mod_ldap (aka. util_ldap) must be loaded in order
for mod_authnz_ldap to function properly
AH00016: Configuration Failed


Regards




On Sun, Sep 13, 2015 at 8:07 AM, Igor Galić <notifications@github.com>
wrote:

> i'm sorry, but i really don't know anything about RHEL :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/puppetlabs/puppetlabs-apache/pull/1199#issuecomment-139823259>
> .
>



-- 
Oded Simon
Mobile: 0410 881 316
E-mail: simonoded@gmail.com

**Comment by igalic** [comment]
@simonoded This should be handled as include in [class apache::mod::authz_ldap](https://github.com/puppetlabs/puppetlabs-apache/blob/master/manifests/mod/authnz_ldap.pp#L4) — a wrapper class that already exists. You should be using that, rather than with the generalized apache::mod define.

**Pull request closed without merging**
