### PR TITLE
MODULES-8541 : Allow HostnameLookups to be modified

### PR DESCRIPTION
**Pull request by k2patel**
https://tickets.puppetlabs.com/projects/MODULES/issues/MODULES-8541

Apache variable HostnameLookups should be allowed to configured, as many of the configuration behind proxy require the domain name lookup in conditional statements. It should be default value set to Off, but it should be allowed to configured.

### CODE REVIEW

**Comment by pmcmaw** [comment]
Hey @k2patel 

I would like to thank you for creating this PR. Before we can consider merging would be be possible to document this new parameter and add in some tests?

Many thanks
The Modules Team

**Comment by david22swan** [comment]
@k2patel is there any movement on this?

**Comment by k2patel** [comment]
@david22swan Sorry about delay, documentation added. it does not require any special test to be defined,

**Comment by david22swan** [comment]
@k2patel Thank for getting back on this and adding the documentation. We do require that feature's such as this possess dedicated test's however. there need's to be at least one example of the value being set to each possibility, checking that the hostnames can be looked up.

**Comment by k2patel** [comment]
@david22swan test added

**Comment by david22swan** [comment]
@k2patel Thank you for getting back to me with the test's unfortunately there will be a short wait on getting this merged however as the module is currently being put through an audit/cleanup. Once that is finished however your pr will be merged in as soon as possible.

**Comment by david22swan** [comment]
@k2patel The audit I previously mentioned has been completed, as such if you could rebase your changes then we could see about getting it merged.

**Comment by k2patel** [comment]
@david22swan - i've tried to do rebase, not sure if i've did it correctly.
Please let me know if there is anything need to be done.

**Comment by david22swan** [comment]
Screen Shot 2019-04-01 at 10 57 07 AM
@k2patel Your changes have passed an adhoc run, as such I feel pretty good about merging them.
Thanks for the work you put in and sorry for the wait.

**Pull request merged**
