### PR TITLE
Add proxy_pass in directory template for location context

### PR DESCRIPTION
**Pull request by toteva**
ProxyPass according to the https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypass is an available directive in the Location context

### CODE REVIEW

**Comment by toteva** [comment]
How can I rerun the checks? I see a strange error in the checks that " The Travis CI build failed" but watching at the logs, I did not see anything that really failed. Immediately after the failed tests the Ruby 2.1.7 was replaced in the gem with 2.1.9

https://github.com/puppetlabs/puppetlabs-apache/pull/1645/commits/ce8224a706e388bc62f05efdc47279d5e08831a9

**Comment by tphoney** [comment]
I restarted the build, to see what happens

**Comment by toteva** [comment]
Thanks. The 2.1.7 seems to have passed.

**Comment by eputnam** [comment]
@toteva thanks for the PR. can you rebase so we can run this against our new travis config?

**Comment by toteva** [comment]
The test with "export PUPPET_GEM_VERSION="~> 4.0" fails with 'The command "bundle exec rake release_checks" exited with 1.' But so it was the last time. There is no visible error. A rerun of the test fixed the problem. 

Could you please rerun it or help me understand what I am doing wrong?

Thanks

**Comment by eputnam** [comment]
i'm confused myself, i'll rekick though. let me know if you find anything.

**Comment by toteva** [comment]
Thanks. It has worked out. I do not know what could be causing this..

**Pull request merged**
