### PR TITLE
Wsgi inclusion

### PR DESCRIPTION
**Pull request by willmeek**

### CODE REVIEW

**Comment by ekohl** [comment]
Should I close https://github.com/puppetlabs/puppetlabs-apache/pull/1693 since this includes it and adds tests?

**Comment by tphoney** [comment]
we can close it when CI is better.

**Comment by tphoney** [comment]
This closes #1693

**Comment by ekohl** [comment]
Thanks for adding tests @willmeek!

**Comment by willmeek** [comment]
Thanks @ekohl !

**Pull request merged**
