### PR TITLE
Add ShibCompatValidUser option to vhost config

### PR DESCRIPTION
**Pull request by mdechiaro**

### CODE REVIEW

**Comment by david22swan** [comment]
@mdechiaro Please rebase your changes and resolve the conflicts.
In addition could you add test coverage to your changes.

**Comment by mdechiaro** [comment]
@david22swan I'll work on getting those tests added hopefully in the next few weeks.

**Comment by david22swan** [comment]
@mdechiaro Good to hear

**Comment by david22swan** [comment]
Closing and reopening PR to solve bundler issue

**Comment by mdechiaro** [comment]
@david22swan I am having some trouble with the spec tests, and hopefully you can provide some
assistance. The shibboleth code lack examples of tests for other parameters that I can reference.

What I am trying to accomplish is test that the parameter ShibCompatValidUser can be set inside 
apache::vhost when declared, but I can't get the spec tests to pass. I was able to 
successfully create an acceptance test with the following code:
```
  # spec/acceptance/vhost_spec.rb
  describe 'shibboleth parameters' do
    it 'applies cleanly' do
      pp = <<-EOS
        class { 'apache': }
        class { 'apache::mod::shib': }
        apache::vhost { 'test.server':
          port    => '80',
          docroot => '/var/www/html',
          shib_compat_valid_user => 'On'
        }
      EOS
      apply_manifest(pp, :catch_failures => true)
    end
    describe file("#{$vhost_dir}/25-test.server.conf") do
      it { is_expected.to be_file }
      it { is_expected.to contain 'ShibCompatValidUser On' }
    end
  end
```

How should I set the spec test to validate this parameter?

**Comment by david22swan** [comment]
@mdechiaro I'm afraid I don't understand what you mean, is the example test you posted working? And by spec test's do you mean unit, if so what you already have is enough in my opinion.

**Comment by mdechiaro** [comment]
@david22swan Yes, I was referring to unit testing. I committed the acceptance test, and let me know if you need anything else.

**Pull request merged**
