### PR TITLE
Fix PassengerRoot under Debian stretch

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by mmoll** [comment]
As all newer versions have locations.ini, it could make sense to double-reverse the logic here to be more future-safe.

**Comment by sathieu** [comment]
@mmol: hello again ;-) Done.

**Comment by tphoney** [comment]
woops, i made a bad click. apologies

**Comment by tphoney** [comment]
@sathieu great work ! thanks for the change, i can forsee this being expanded out again, at some point. For now, it looks a lot better.

**Pull request merged**
