### PR TITLE
(MODULES-2703) Allow duplicate additional configuration directive names for PageSpeed

### PR DESCRIPTION
**Pull request by abednarik**
PageSpeed template updated to support multiple lines for the same directive.
There is no Tests for pagespeed directives. Please see Jira issue comments if you want to help me out adding more tests.

### CODE REVIEW

**Comment by igalic** [comment]
@abednarik would you mind doing a proper [rebase](https://www.git-scm.com/book/en/v2/Git-Branching-Rebasing)?

**Comment by abednarik** [comment]
@igalic  

 Sorry for this :(. If you don't mind can you tell how can I do a proper rebase?

**Comment by igalic** [comment]
@abednarik here's my how-to-squash: https://github.com/puppet-community/puppet-jira/pull/99#issuecomment-152528108 — if you ignore the last command, it's also a how-to-rebase :)

**Comment by abednarik** [comment]
Thanks @igalic and sorry for bother you. I made a rebase with all my commits in my master branch. See https://github.com/abednarik/puppetlabs-apache if you can.
Should i do i need PR?

**Comment by abednarik** [comment]
@igalic  Can you please check if everything is fine now? 

Thanks for your help.

**Pull request closed without merging**
