### PR TITLE
Auto load Apache::Mod[slotmem_shm] and Apache::Mod[lbmethod_byrequest…

### PR DESCRIPTION
**Pull request by sathieu**
…s] with proxy_balancer on 2.4

### CODE REVIEW

**Comment by binford2k** [comment]
Can you update your spec test with something like https://github.com/puppetlabs/puppetlabs-apache/blob/master/spec/classes/mod/worker_spec.rb#L4-L6 so the variable is available to use?

**Comment by hunner** [comment]
And could you document the new parameter in README.md similar to the other mods with parameters? Thanks!

**Comment by sathieu** [comment]
@hunner @binford2k  Comments addressed.

**Comment by HelenCampbell** [comment]
Thanks for your contribution!

**Pull request merged**
