### PR TITLE
fix puppet-lint errors and warnings

### PR DESCRIPTION
**Pull request by costela**
Minor commit to shut-up puppet-lint

### CODE REVIEW

**Comment by igalic** [comment]
i'm fascinated by now *everything* is failing on the future parser.

**Comment by mhaskel** [comment]
Hi @costela, thanks for the contribution. The quotes in `manifests/vhost.pp` are required for future parser, so the correct way to fix that would be to add a `# lint:ignore:only_variable_string` comment on those lines.

**Comment by costela** [comment]
Hi @mhaskel, 
I'm not sure I understand it: I *am* using the future parser (albeit on 3.7) and it doesn't seem to choke on the lack of quotes. Is using quotes in this case the "new right thing"? (maybe I'm using an outdated version of puppet-lint; can't check right now)

**Comment by mhaskel** [comment]
Hi @costela, the issue is that the `$port` and `$listen_addr_port` support either a stringified integer or an integer, and the future parser is not ok with resources with a numeric title (so, like `apache::listen { 80: }`)

**Comment by costela** [comment]
aaah, ok, gotcha! now it makes sense! ;)
thanks @mhaskel! I'll close this PR then

**Pull request closed without merging**
