### PR TITLE
Update _additional_includes.erb

### PR DESCRIPTION
**Pull request by cristi1979**
fix Include statement for apache 2.4

### CODE REVIEW

**Comment by mhaskel** [comment]
@cristi1979 sorry I lost track of this for so long. Couple of comments. I think I misunderstood what you were going to have the parameter do when I suggested the name. I think `$use_optional_includes` or something along that line. This also needs to be squashed down to a single commit, and have updates added to the README for the new parameter.

**Comment by cristi1979** [comment]
Can I close this pull and do a new one? I have no idea how to squash commits from before merge remote-tracking branch

**Comment by cristi1979** [comment]
Ping. is it ok to do a new pull request for this? Because I can't merge all commits from here.

**Comment by mhaskel** [comment]
@cristi1979 yes, you can close this and open another. Alternatively, you can follow this [workflow](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) to rebase and squash the PR. If you do open a new one just close this PR and reference the new PR in a comment.

**Comment by cristi1979** [comment]
rebase done. Thank you for the link

**Comment by cristi1979** [comment]
looks like travis failed for PUPPET_GEM_VERSION="~> 2.7.0". But it doesn't seem to be from any checks, but from the bootstrap part. Should I make a new dummy commit to see if it was something from their side?

**Comment by cristi1979** [comment]
force a travis rerun and now the check is green

**Comment by mhaskel** [comment]
@cristi1979 thanks for the update! One last thing, can you add documentation in the [README](https://github.com/puppetlabs/puppetlabs-apache#class-apache) for the new parameter?

**Comment by cristi1979** [comment]
ping

**Comment by mhaskel** [comment]
Thanks for the contribution @cristi1979!

**Pull request merged**
