### PR TITLE
1.8.x README revisions

### PR DESCRIPTION
**Pull request by gguillotte**
Needs review, then I can squash and merge.

This PR adds defaults, updates numerous links, adjusts formatting and style, and makes a few edits to text.

### CODE REVIEW

**Comment by gguillotte** [comment]
CC @jbondpdx

**Comment by gguillotte** [comment]
Addressed the things @jbondpdx caught and pushed a new commit.

**Comment by jbondpdx** [comment]
+1 on merging

**Comment by bmjen** [comment]
@gguillotte can you squash these commits before I merge?

**Comment by gguillotte** [comment]
@bmjen Will do!

**Comment by gguillotte** [comment]
@bmjen Commits squashed!

**Pull request merged**
