### PR TITLE
MODULES-3212: add parallel_spec option

### PR DESCRIPTION
**Pull request by jlambert121**

### CODE REVIEW

**Comment by igalic** [comment]
how much of this can we push into modulesync_configs?

**Comment by jlambert121** [comment]
@igalic: https://github.com/puppetlabs/modulesync_configs/pull/55

**Comment by jonnytpuppet** [comment]
@jlambert121  it would be appreciated if you could rebase this against current master as changes have gone in that should fix the failing unit tests (assuming nothing in this PR breaks them).

Thanks

**Comment by igalic** [comment]
i'm very excited about this

**Comment by jlambert121** [comment]
@igalic yeah - spec tests on this module are painful to run and wait for.  I did submit a PR against modulesync_configs as well to enable it everywhere as well.

**Pull request merged**
