### PR TITLE
Add attributes owner and group to apache::custom_config

### PR DESCRIPTION
**Pull request by aklein-dex**
These attributes are used for the resource type `file`.

### CODE REVIEW

**Comment by eputnam** [comment]
@aklein-dex , thanks for the PR! could you please rebase? also, what motivated you to add these params?

**Comment by aklein-dex** [comment]
if the file is owned by user bob UID 1005 on the Puppet server, then it will be owned by the user with UID 1005 on the node where the file is deployed. But on that node maybe UID 1005 is Max. That can lead to a security risk.
So it would be nice to be able to specify the owner (and group) of the file.

**Comment by ekohl** [comment]
@aklein-dex it looks like you merged in master but it'd be better to rebase. Now there are a lot of commits which makes reviewing very hard. Other than that to me it makes sense to set the owner/group explicitly.

**Comment by aklein-dex** [comment]
@ekohl yes sorry for that. Let me close it and create another one.

**Pull request closed without merging**
