### PR TITLE
Rework passenger VHost and Directories

### PR DESCRIPTION
**Pull request by smortex**
This Pull-Request allow setting [all supported parameters](https://www.phusionpassenger.com/library/config/apache/reference/) to VirtualHosts and Directories.

It also fixes a few things and has a few enhancements:
* Add types for VHost parameters;
* Remove deprecated parameters;
* Reorder parameters to follow the order used in the documentation;
* Improve unit tests coverage.

The combined commits is a pain to read, but hopefully reviewing commits one by one should be easier :-)

### CODE REVIEW

**Comment by david22swan** [comment]
Looks fine to me but would like a +1 from someone else

**Comment by vidkun** [comment]
I can't speak to the code quality, but I could really use this capability right now.

**Comment by david22swan** [comment]
@hunner Could you give this a quick look please?

**Comment by vidkun** [comment]
Any chance of this getting merged?

**Comment by HelenCampbell** [comment]
Hey @smortex , I'd be keen to get your changes in, would you have any time to rebase this for us then I can re-review for merge? Thanks!

**Comment by smortex** [comment]
Hi @HelenCampbell! I just rebased the branch on top of master.   Thanks!

**Comment by HelenCampbell** [comment]
@smortex Reviewed and ran this PR through an adhoc jenkins pipeline with no issues. I'm happy with the changes so I'll get this merged. Thank you for all the work you put into this!

**Pull request merged**
