### PR TITLE
Define SCL package name for mod_ldap

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by turnopil** [comment]
Maybe would be a good decision add support for Amazon AMIs because in AWS apache2.4 mod_ldap package called 'mod24_ldap' but for 2.2 - mod_authz_ldap

**Comment by lionce** [comment]
Hello @treydock ,

Thank you for your contribution. In order to merge this PR, please resolve the conflicts. 

Cheers!

**Comment by treydock** [comment]
@lionce Looks like the acceptance tests for SCL logic were removed but there are no corresponding unit tests.  6006ca218f6893566e7b1d9b9fdf9f41dc4255ff leads me to believe this was intentional but I'm not seeing unit tests to replace the acceptance tests.  Should I go ahead and remove my changes that conflict even though no test coverage?

**Comment by lionce** [comment]
Hello @treydock ,

Yes, we removed some acceptance tests because they were testing  the connection to a specific port, or the server answer. Most of them were replaced by unit tests. In order to increase the test coverage, I would really appreciate if you will add a unit test to cover this case. Many thanks! 

Cheers!

**Comment by treydock** [comment]
@lionce Added unit tests for changes in this PR.

**Comment by treydock** [comment]
Also had to add `$conf_enabled` as needed by main apache class and was throwing undefined variable errors.

**Comment by lionce** [comment]
Hello @treydock ,

Thank you for this PR. It looks good to me! 

Cheers

**Pull request merged**
