### PR TITLE
MODULES-9003 Parameterize location for ldap-status

### PR DESCRIPTION
**Pull request by youeyoue**
Add ldap_path parameter to apache::mod::ldap with
Change ldap.conf.erb to use new parameter
Add new parameter to README.md

### CODE REVIEW

**Comment by sheenaajay** [comment]
@youeyoue Thanks for your contribution. Could you please resolve the conflicts. Thank you.

**Comment by youeyoue** [comment]
Conflicts resolved.  The ldap_path param doc is now in the module manifest (no longer in README.md).

**Comment by sheenaajay** [comment]
Hi @youeyoue 
Changes look good. Could you please update the unit tests also in this file
https://github.com/puppetlabs/puppetlabs-apache/blob/master/spec/classes/mod/ldap_spec.rb#L54

For example
Update the params in the list
and check for the contents
` ldap_path: '/ldap-status',

it { is_expected.to contain_file('apache-mod-ldap.conf').with_content(%r{^Location /ldap-status$}) }
`

**Comment by youeyoue** [comment]
Added a unit test with a custom ldap_path.

**Pull request merged**
