### PR TITLE
Add basic initial support for SLES 11

### PR DESCRIPTION
**Pull request by carroarmato0**
Add just about enough support to have a working compilation, basic install of Apache.

Installing and managing a vhost has been tested.

Signed-off-by: Christophe Vanlancker <christophe.vanlancker@inuits.eu>

### CODE REVIEW

**Comment by igalic** [comment]
@carroarmato0 would you mind [squashing](http://www.git-scm.com/book/en/Git-Tools-Rewriting-History#Squashing-Commits) those commits down to one?

**Comment by carroarmato0** [comment]
@igalic oh wow, those builds took awhile. But hey, squashed the changes as requested

**Comment by igalic** [comment]
thanks for the patch @carroarmato0!

**Comment by carroarmato0** [comment]
@igalic yw

**Pull request merged**
