### PR TITLE
Added `apache::mod::proxy_wstunnel` class

### PR DESCRIPTION
**Pull request by netors**

### CODE REVIEW

**Comment by igalic** [comment]
we'll need a docs update here as well

**Comment by tphoney** [comment]
looks like you missed your new doc changes

**Comment by mentat** [comment]
Hi it doesn't look like your new class is documented in the readme.  Could you document and squash your changes?  Thanks.

**Comment by tphoney** [comment]
@netors, thanks for the work you have put into this pull request. However due to inactivity and missing  documentation this pull request is being closed. If you want to re-submit this PR with the necessary changes, we will gladly look at the new pull request.

**Pull request closed without merging**
