### PR TITLE
(MODULES-10899) Clean up PHP mod id handling in apache::mod::php

### PR DESCRIPTION
**Pull request by beatchristen**
I've added two tests and my try on fixing it:
- Debian 10 out of the box with the php 7.3 variant
- Debian 10 / experimental php 8.0 packages, configured via `$php_version = '8.0'`

Note on `/etc/apache2/mods-enabled/php.load`:
the code currently doesn't name the file as `php8.0.load` like the standard package would call it.
Doing so would also require to override the variable `$loadfile_name`, which looks silly. 

Note on `$mod` and `$_module_id`: 
Didn't notice this was only added in the PR, there's potential for cleaning up?

### CODE REVIEW

**Comment by sanfrancrisko** [comment]
@beatchristen If you don't override the name of `$loadfile_name` will this not fail on Debian 10 (using the sid repo)?

Using `a2enmod php8.0` after installing `apt install libapache2-mod-php8.0`, this is the contents of `/etc/apache2/mods-enabled/php8.0.load`:
```
# Conflicts: php5
# Depends: mpm_prefork
LoadModule php_module /usr/lib/apache2/modules/libphp8.0.so
```

**Comment by beatchristen** [comment]
Thought so too at first when I was switching around on the different PHP implementations for debian from https://deb.sury.org/

So switching with the original mainline apache module also leaves around the "old" files in `/etc/apache2/mods-available`.
But this works nevertheless, as the relevant directory `/etc/apache2/mods-enabled` is  a managed directory and purges the older softlinks, as you can only have one `apache::mod::php` which places the softlink.

```
root@debian10:/etc/apache2/mods-available# ls -al /etc/apache2/mods-enabled/php*
lrwxrwxrwx 1 root root 36 Feb 15 17:41 /etc/apache2/mods-enabled/php.conf -> /etc/apache2/mods-available/php.conf
lrwxrwxrwx 1 root root 36 Feb 15 17:41 /etc/apache2/mods-enabled/php.load -> /etc/apache2/mods-available/php.load
root@debian10:/etc/apache2/mods-available# ls -al /etc/apache2/mods- 
mods-available/ mods-enabled/   
root@debian10:/etc/apache2/mods-available# ls -al /etc/apache2/mods-available/php*
-rw-r--r-- 1 root root 545 Feb 15 17:41 /etc/apache2/mods-available/php.conf
-rw-r--r-- 1 root root  60 Feb 15 17:41 /etc/apache2/mods-available/php.load
-rw-r--r-- 1 root root 545 Feb 12 16:43 /etc/apache2/mods-available/php7.4.conf
-rw-r--r-- 1 root root  61 Feb 12 16:43 /etc/apache2/mods-available/php7.4.load
-rw-r--r-- 1 root root 855 Feb 12 14:51 /etc/apache2/mods-available/php8.0.conf
-rw-r--r-- 1 root root 101 Feb 12 14:51 /etc/apache2/mods-available/php8.0.load
```

So based on the same logic of "you can't have more than one PHP apache module at any one time anyway", there's no point in having the version number as part of the load file, as this leaves above mentioned traces behind.

Only reason to tweak the `$loadfile_name` would be to be compatible to instructions on the web that says go to that file there at `/etc/apache2/mods-*/php*.load`. But that's IMHO not the same audience of sysadmins that puppet gets 😅.

**Comment by sanfrancrisko** [comment]
Thanks for the explanation @beatchristen - makes more sense now 👍 😃

**Comment by sanfrancrisko** [comment]
@beatchristen I'm happy with this change (tested myself locally too). Would you be OK changing the base to `sanfrancrisko:MODULES-10899/main/apache_php8_mod_name` and rewriting the commit to be a bit more descriptive, and I'll get it pulled in as one commit. 

Alternatively, I can merge #2121 and then we can merge this PR after.

**Comment by beatchristen** [comment]
#2121 is contained in #2124 as it also has your last commit 721878a05d2d456ff1f30bc062461e983676fae4.

Or would you like to have it flattened down to one?

**Comment by sanfrancrisko** [comment]
What I'll do is bring all the commits over as one in #2121 . There's actually three PRs this has spread across (in chronological order):

- #2119 
- #2121 
- #2124 

I will likely keep everything as atomic commits going in (might squash mine to one) as they are standalone, but I'll use #2124 to do all that in.

All credit will still go to you and @cdamage for the contributions against the entire bit of work 😄

**Comment by beatchristen** [comment]
just saw your edit: my branch started off from `sanfrancrisko:MODULES-10899/main/apache_php8_mod_name`.
However it's not possible for me to open the pull request towards your repo & branch. 
You would need to add my fork as another remote or fork from my repo to get the commit over.

**Comment by sanfrancrisko** [comment]
> just saw your edit: my branch started off from `sanfrancrisko:MODULES-10899/main/apache_php8_mod_name`.
> However it's not possible for me to open the pull request towards your repo & branch.
> You would need to add my fork as another remote or fork from my repo to get the commit over.

**Comment by sanfrancrisko** [comment]
> just saw your edit: my branch started off from `sanfrancrisko:MODULES-10899/main/apache_php8_mod_name`.
> However it's not possible for me to open the pull request towards your repo & branch.
> You would need to add my fork as another remote or fork from my repo to get the commit over.

Ah, OK. I thought that was maybe just permission issues for me. 

I've cherry picked your commit in to my branch now, so Github should automatically close the two other PRs (including yours) when this is merged.

Thanks again @beatchristen !

**Comment by beatchristen** [comment]
Closing as delivered to main via #2121. Thanks for the quick merge @sanfrancrisko

**Pull request closed without merging**
