### PR TITLE
#FORGE-288 Apache::vhost module should support raw vhost configuration

### PR DESCRIPTION
**Pull request by yrobla**
Add a new raw_vhost parameter to apache::vhost . This parameter will be a string, that will allow to configure a vhost externally, passing a string with the final content.
For certain use cases, it will be simpler and will add also the flexibility needed.

### CODE REVIEW

**Comment by igalic** [comment]
@yrobla thank you very much for this patch
please note that it's not merging cleanly anymore, and hence needs a [rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing). I'd also very much appreciate a [squash](https://www.git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits).

you're also introducing this new feature that changes a lot of existing code, without any tests :|

**Comment by pabelanger** [comment]
+1

**Comment by dteirney** [comment]
Is there something that this approach achieves that the existing $custom_fragment can't address? I've managed to get quite far with the various standard parameters and then putting what else was needed into the custom_fragment.

**Comment by yrobla** [comment]
I will be closing. As discussed on the modules meeting, a new vhost::custom will be created, to allow to pass raw configuration.

**Comment by igalic** [comment]
pinging @hunner who wanted to submit this pr :)

**Comment by hunner** [comment]
@igalic Sorry, I think @pabelanger had volunteered to make `apache::vhost::custom` that wrapped `apache::custom_config`

**Comment by pabelanger** [comment]
Ya, I've started something already. Hope to have something in the next few days.

**Pull request closed without merging**
