### PR TITLE
Simplify templates by reusing methods

### PR DESCRIPTION
**Pull request by ekohl**
See individual commits for details. Note I haven't tested this and will rely on CI and review to spot errors.

### CODE REVIEW

**Comment by david22swan** [comment]
@ekohl Look's like your change may be causing some failures on Debian and Ubuntu

**Comment by ekohl** [comment]
I've submitted the first part as https://github.com/puppetlabs/puppetlabs-apache/pull/2366. Once that's merged I'll rebase this and see where it fails.

**Comment by ekohl** [comment]
Rebased and pushed a fix in the WSGI template that I think was the cause for the failure. If this is green, it's ready to be merged.

**Review by david22swan — APPROVED** [review]
Logic for this look's good to me and the tests are green.
Happy to merge, just had to hit the rebase button first.

**Comment by ekohl** [comment]
@david22swan rebase passed.

**Comment by david22swan** [comment]
Apologies on the wait, this slipped my mind

**Comment by ekohl** [comment]
I've been there way too often.

**Pull request merged**
