### PR TITLE
Remove prefix for SSLSessionCache parameter

### PR DESCRIPTION
**Pull request by geekix**
Hi everyone,

I came across a problem with the mod_ssl cache and SNI. I need to disable this cache, and I was very surprised to see that in the mod_ssl template, the SSLSessionCache parameter in prefixed with a value :

`SSLSessionCache "shmcb:<%= @ssl_sessioncache %>"`

As you will se in the Apache [documentation](https://httpd.apache.org/docs/2.4/en/mod/mod_ssl.html#sslsessioncache), the parameter can take other values ("none" being the one I need to disable the mod_ssl cache).

I think we should be able to configure any supported value.

Thanks

Damien

### CODE REVIEW

**Comment by geekix** [comment]
Hi everyone,

I also changed the default SSLSessionCache parameter value, the initial prefix is now included in the default value :

$ssl_sessioncache    = "shmcb:\${APACHE_RUN_DIR}/ssl_scache(512000)"

**Comment by HelenCampbell** [comment]
Hey @geekix , I'd be keen on getting this PR in as I'm doing some major work on Apache and the extra configurability here is great. Would you be able to fix the test failure you have? Looks like it may be as simple as updating the test param.
Thanks!

**Comment by david22swan** [comment]
@geekix Sorry to bother you but I was wondering if there was any movement on this PR?

**Comment by pmcmaw** [comment]
Closed and reopened to trigger tests to check the test failures.

**Comment by pmcmaw** [comment]
@geekix due lack of movement I am going to close this PR. 
If you get time in the future or disagree with my decision please do not hesitate to reopen. 

We would like to thank you for taking the time to contribute to our supported module. 
The Modules Team.

**Pull request closed without merging**
