### PR TITLE
Remove SSLv3

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by hunner** [comment]
@igalic So, this sounds nice; do you think this would be "backwards incompatible change" or "security bugfix" or what?

**Comment by roidelapluie** [comment]
Security Bugfix. POODLE.

**Comment by roidelapluie** [comment]
However we could give people to ability to re-add the sslv3 in libnss with a parameter?

**Comment by igalic** [comment]
pretty sure we've deprecated sslv3 a couple of years ago: https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslprotocol

**Comment by ghoneycutt** [comment]
Thanks!

**Comment by hunner** [comment]
[RFC-7525](https://tools.ietf.org/html/rfc7525) would not even allow SSLv3 as a fallback, so yeah not allowing this to be turned on is a good idea.

**Pull request merged**
