### PR TITLE
create resources for balancers

### PR DESCRIPTION
**Pull request by tibers**
Similar to vhosts, add a convenience method to create resources for balancers.

### CODE REVIEW

**Comment by tibers** [comment]
I absolutely suck at writing unit tests and would appreciate the help.

**Comment by eputnam** [comment]
@tibers , thanks for the PR! Would you mind adding this new class to the README? And I'd be happy to take a look at your tests next week to get those sorted.

**Comment by david22swan** [comment]
@tibers Is there any movement on this PR?

**Comment by david22swan** [comment]
@tibers I apologize but due to the lack of movement on this PR I will be closing it. If you ever again have the time to return to it I hope you will resubmit it to be reviewed once again.

**Pull request closed without merging**
