### PR TITLE
added extra var.:mod_full_path, where you can define the full path to…

### PR DESCRIPTION
**Pull request by gvdb1967**
if os=redhat || centos 
use the mod_full_path var. to set the path to the shibboleth module 
ex. apache::mod::shib::mod_full_path: /usr/lib64/shibboleth/mod_shib_22.so

### CODE REVIEW

**Comment by gvdb1967** [comment]
fixed syntax warning/error

**Comment by gvdb1967** [comment]
changed fail to warning

**Comment by bmjen** [comment]
Thanks @gvdb1967 . With this change creating a difference between red hat and debian, can you add some documentation to the README about the need for this parameter in Red Hat? Also, there needs to be at least unit test testing that the parameter is set when passed in.

**Comment by gvdb1967** [comment]
Hi,

I will fix/change it next week. I also have some problems with this pull
request https://github.com/puppetlabs/puppetlabs-apache/pull/1361
It's the first time I work on github😓 ....

2016-02-08 19:07 GMT+01:00 Bryan Jen <notifications@github.com>:

**Comment by bmjen** [comment]
@gvdb1967 Has there been any progress on this PR? I'm going to close this PR for inactivity for now, please feel free to reopen it when you have time to readdress. Thanks!

**Pull request closed without merging**
