### PR TITLE
allow include in vhost directory

### PR DESCRIPTION
**Pull request by Zarne**

### CODE REVIEW

**Comment by sgerhards** [comment]
Could you please supply some tests for the additional key in the directory hash?

Thanks

**Comment by hunner** [comment]
Thanks! This looks good so far. Could you also update the readme to document that these two values can be passed as part of the directories hash at https://github.com/puppetlabs/puppetlabs-apache#parameter-directories-for-apachevhost

**Comment by jonnytpuppet** [comment]
@zarne Hi there, have you had a chance to look at this yet? Thanks!

**Comment by tphoney** [comment]
@Zarne thanks for the work, i am merging this !

**Pull request merged**
