### PR TITLE
WIP "Use beaker testmode-switcher"

### PR DESCRIPTION
**Pull request by nibalizer**

### CODE REVIEW

**Comment by tphoney** [comment]
i see you are fighting the good fight here !

**Comment by bmjen** [comment]
@nibalizer Is this still something being worked on?

**Comment by igalic** [comment]
@nibalizer welcome back to Americaland. are you still interested in pushing this?

**Comment by bmjen** [comment]
@nibalizer I'm going to close this until it's ready to be revived.

**Pull request closed without merging**
