### PR TITLE
(MODULES-11068) Allow apache::vhost ssl_honorcipherorder to take boolean parameter

### PR DESCRIPTION
**Pull request by davidc**
* Allow ssl_honorcipherorder on apache::vhost to take booleans as every other on/off parameter does.
* Default to not outputting SSLHonorCipherOrder at all, as before.
* Also accept on/off to maintain backwards compatibility. (Note, the code would previously accept any value and output it verbatim. But since Apache will only accept on/off, I don't think it's necessary to maintain *that* level of backwards-compatibility).
* Add tests for the new functionality as well as backwards compatibility - this need scrutiny as I have not written rspec tests before.

(fixes MODULES-11068)

### CODE REVIEW

**Comment by davidc** [comment]
I am confused why these tests are failing when they run OK on my machine:

```
$ pdk test unit --tests=defines/vhost_spec.rb -v
[...]
      ssl_honorcipherorder
        ssl_honorcipherorder default
          is expected to compile into a catalogue without dependency cycles
          is expected to contain Concat::Fragment[rspec.example.com-ssl] with content !~ /^\s*SSLHonorCipherOrder/i
        ssl_honorcipherorder on
          is expected to compile into a catalogue without dependency cycles
          is expected to contain Concat::Fragment[rspec.example.com-ssl] with content =~ /^\s*SSLHonorCipherOrder\s+On$/
        ssl_honorcipherorder true
          is expected to compile into a catalogue without dependency cycles
          is expected to contain Concat::Fragment[rspec.example.com-ssl] with content =~ /^\s*SSLHonorCipherOrder\s+On$/
        ssl_honorcipherorder off
          is expected to compile into a catalogue without dependency cycles
          is expected to contain Concat::Fragment[rspec.example.com-ssl] with content =~ /^\s*SSLHonorCipherOrder\s+Off$/
        ssl_honorcipherorder false
          is expected to compile into a catalogue without dependency cycles
          is expected to contain Concat::Fragment[rspec.example.com-ssl] with content =~ /^\s*SSLHonorCipherOrder\s+Off$/
[...]
Finished in 40 minutes 11 seconds (files took 43.3 seconds to load)
4527 examples, 0 failures
```

**Comment by davidc** [comment]
It seems there was a further test in spec/acceptance/apache_ssl_spec.rb that is setting apache::vhost ssl_honorcipherorder to "test", I have changed it to check boolean true => On instead.

I can't test this locally since it seems to want to actually apply a configuration to my machine, so I'll push the change and let CI run it again.

**Comment by DavidS** [comment]
I'll take a look at it today.

**Comment by DavidS** [comment]
github actions is currently experiencing issues - see https://www.githubstatus.com/ ; that might explain the delays and weird failures. I'll re-run the checks once the github incident has cleared up.

**Comment by DavidS** [comment]
rekicked all the github actions

**Review by DavidS — APPROVED** [review]

**Comment by DavidS** [comment]
The failures all look like still impacts from the github incident rather than actual code issues. Since this is not a platform-dependent change, I'm gonna merge it and continue to monitor scheduled CI for tomorrow.

**Comment by DavidS** [comment]
Thanks a lot @davidc for your contribution and apologies for the bumps along the way!

**Pull request merged**
