### PR TITLE
Add cas_cookie_path_mode param

### PR DESCRIPTION
**Pull request by edestecd**
We need this to open up write to all in the apache group.

### CODE REVIEW

**Comment by tphoney** [comment]
@edestecd great work here. I have a couple of suggested changes:
- could you squash your commits
- could you edit the readme to add the new attributes to the documentation line 1417-1430
Other than that, thanks for the effort and time you put in.

**Comment by tphoney** [comment]
wooops, accidental close

**Comment by tphoney** [comment]
@edestecd thanks for the work !!! unfortunately the code base has moved on, you will need to rebase.

**Comment by edestecd** [comment]
@tphoney rebased!

**Comment by edestecd** [comment]
I'm not sure why the test are failing.  It looks like a network connectivity issue with ssh and not related to my code changes...

**Comment by edestecd** [comment]
Can you force a rerun of the tests?

**Comment by tphoney** [comment]
re-run, i will look into it tomorrow, if the tests continue to fail

**Comment by edestecd** [comment]
looks like other PRs fail with similar errors, not sure how my change could have caused httpd to not be installed or the service not started etc.  Looks like a very systemic issue.

**Comment by tphoney** [comment]
@edestecd there is a possible issues in the latest specinfra, that could be affecting this. We have a possible fix in flight.

**Comment by edestecd** [comment]
@tphoney Awesome, thanks for your help on this.

**Pull request merged**
