### PR TITLE
Allow additional settings for GSSAPI in Vhost

### PR DESCRIPTION
**Pull request by tuxmea**
Adding config items:
- allowedmech
- authname
- authtype
- basicauth

### CODE REVIEW

**Review by bastelfreak — APPROVED** [review]

**Comment by david22swan** [comment]
@tuxmea Sorry for the wait on review. Anyway this change look's good to me but could you also update the relevant documentation linked below? Would be sad if you put in a great change like this and nobody could find it:

- https://github.com/puppetlabs/puppetlabs-apache/blob/488a1f55a5839ea9e254da542fc6a355a0a45bdb/manifests/vhost.pp#L1507

**Comment by david22swan** [comment]
@tuxmea Sorry to come back but while reviewing other prs I noticed that a similar change had been pushed up by another contributor that contains part of the functionality that you yourself have added. Just felt I should alert you as depending on which PR is merged first you may need to rebase your work.
Have placed a similar comment on the other PR, linked below:

- https://github.com/puppetlabs/puppetlabs-apache/pull/2214

**Comment by david22swan** [comment]
@tuxmea Hey, just giving an update but on of the PRs I previously mentioned has been merged in so that now `allowedmech` and `basicauth` are already included as options.
If you could rebase your code and add the documentation I had previously mentioned however I would be happy to merge this in and get the remaining two options you have tried to add into the codebase.

**Review by ekohl — CHANGES_REQUESTED** [review]
There is now a merge conflict. While some more parameters have been added, at least `AuthName` and `AuthType` have not so there's still value in this PR. Please rebase to resolve the conflicts.

**Comment by tuxmea** [comment]
@david22swan @ekohl many thanks for your feedback. PR is rebased and ready to get merged. I also updated the documentation in manifests/vhost.pp

**Comment by tuxmea** [comment]
Failed test for OracleLinux 6:
```
Setting up Install Process

stderr:rpmdb: unable to join the environment
error: db3 error(11) from dbenv->open: Resource temporarily unavailable
error: cannot open Packages index using db3 - Resource temporarily unavailable (11)
error: cannot open Packages database in /var/lib/rp
```

**Review by ekohl — APPROVED** [review]
The spec failure looks odd. I'm not sure how this PR could have caused that and we also see it in nightly: https://github.com/puppetlabs/puppetlabs-apache/runs/7381259870?check_suite_focus=true (that said, it is still odd that in Puppet 6 it fails, but doesn't in 7).

**Pull request merged**
