### PR TITLE
add proper array support for require

### PR DESCRIPTION
**Pull request by Griphon**
now valid access rules are generated from directory template

### CODE REVIEW

**Comment by igalic** [comment]
given that this file seems a frequent cause of issues, we should probably add tests for it…
***
general comments: @Griphon: you may wanna [add your email address to your github settings](https://help.github.com/articles/setting-your-email-in-git/), so your commits are associated with your account.
i also suggest using the [github flow](https://guides.github.com/introduction/flow/index.html) workflow for your next pull request.

**Comment by Griphon** [comment]
@igalic, ok, should I write tests for this patch? It does work for my local puppet environment and array of "Require" will work on any apache

**Comment by mhaskel** [comment]
@Griphon Thanks for the contribution! If you could update tests in https://github.com/puppetlabs/puppetlabs-apache/blob/master/spec/defines/vhost_spec.rb to check that the expected file contents are there if `require` is an array or a string. Let us know if you need any additional help!

**Comment by mhaskel** [comment]
@Griphon I updated the tests in #1047, but thanks for the contribution!

**Comment by Griphon** [comment]
@mhaskel Thank you, I'm pleased to contribute but sorry for absence of tests, I had hard time at my work.

**Pull request closed without merging**
