### PR TITLE
updating the test to use ipv4 addresses

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by igalic** [comment]
why's that?

**Comment by tphoney** [comment]
@igalic the ipv6 addresses were causing issues on older OSes in the acceptance tests. Ubuntu 10/12. The test that was added was just to check multiple ip's. not an ipv6 test

**Comment by igalic** [comment]
@tphoney given that we've reached IPv4 exhaustion, the high council has decreed

> that Operating Systems without IPv6 support shall be removed from all test matrices

> that Operating Systems without IPv6 support shall be removed from all provisioning software

thank you for your attention,

:womans_hat:

**Comment by tphoney** [comment]
@igalic i agree, there should be separate IPv6 tests.

**Pull request merged**
