### PR TITLE
(MODULES-2757) Adding if around ServerName in template

### PR DESCRIPTION
**Pull request by damonconway**
Changing template to wrap ServerName in an if statement so you can set $::apache::vhost::servername to false and skip adding ServerName to the config.

### CODE REVIEW

**Comment by igalic** [comment]
@damonconway what's the benefit of doing that?

**Comment by damonconway** [comment]
As I explained in the ticket, we were unable to get the cluster module
packaged with jboss enterprise to work unless we completely removed the
ServerName line. I tried a servername of _default_, but that didn't work
either.

Thanks,
Damon

**Comment by igalic** [comment]
*nod*

would you mind rebasing?

**Comment by damonconway** [comment]
Absolutely. I've not done a rebase before. I assume you want me to bring my branch up to date with master, correct?

**Comment by damonconway** [comment]
Found the docs and did the rebase.

**Comment by igalic** [comment]
thanks @damonconway!

**Pull request merged**
