### PR TITLE
pdksync - Add weekly scheduled workflows

### PR DESCRIPTION
**Pull request by carabasdaniel**
Add weekly scheduled workflows
pdk version: `1.16.0`

### CODE REVIEW

**Comment by carabasdaniel** [comment]
Hi @ekohl 

With Github actions self-hosted runners, as we have set up, only the default branch of the repository will be used in the scheduled triggered build.

**Comment by ekohl** [comment]
But if someone forks this repository (or updates their default branch), will their fork also attempt to run it?

**Comment by carabasdaniel** [comment]
This workflow is using the self-hosted runner and that is tied only to this repository so it should not attempt to run it.

**Comment by ekohl** [comment]
That doesn't really answer my question. Any user or organization can have self hosted runners.

**Comment by carabasdaniel** [comment]
Workflows don't run on a forked repository by default. See the details for scheduled workflows here: https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

**Comment by ekohl** [comment]
I didn't get that from those docs, which is why I was still unsure about it. It's good to know because in theforeman we're also considering switching over. In Voxpupuli we do have a few modules that are forks and Puppetlabs does too (https://github.com/puppetlabs/puppetlabs-apt)

**Pull request merged**
