### PR TITLE
Added support for LDAPTrustedGlobalCert option to apache::mod::ldap

### PR DESCRIPTION
**Pull request by lukebigum**
This adds the Apache mod LDAP option described here: https://httpd.apache.org/docs/2.2/mod/mod_ldap.html#ldaptrustedglobalcert

Not sure of the best place to document the functionality though?

### CODE REVIEW

**Comment by tphoney** [comment]
@lukebigum the best place to document the functionality is in the README there are a number of modules already there. You can use them as a template.

**Comment by lukebigum** [comment]
Now with documentation.

**Comment by igalic** [comment]
@lukebigum would you very much mind [squashing](https://www.git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits) those commits down to 1?
n.b.: it might be easier to do this (in the future) if you follow the [github flow](https://guides.github.com/introduction/flow/index.html) work-flow.

**Comment by lukebigum** [comment]
No problem, squashed.

**Pull request merged**
