### PR TITLE
[#puppethack] Adding ability to enable/disable the secruleengine through a parameter

### PR DESCRIPTION
**Pull request by igalic**
rebase / squash of #1120.

### CODE REVIEW

**Comment by igalic** [comment]
still no tests though, cuz, i'm finding them quite pointless in this case.
@bmjen seens to disagree…

**Comment by bmjen** [comment]
@igalic I don't think I ever disagreed. :P 

I think after looking at the spec tests for mod_security, a unit test is likely not necessary. Will merge once travisci is done.

**Comment by jackdpeterson** [comment]
Can this be merged in? I'd like to be the first test-case :-)

**Comment by igalic** [comment]
yes, yes it can. (now that travis is done)

**Pull request merged**
