### PR TITLE
feat: add Debian12 Compability

### PR DESCRIPTION
**Pull request by Robnarok**
## Summary
The current version is not suitable for Debian 12, which was released a few weeks ago. Unfortunately the new Debian Requires PHP 8.2

## Additional Context
Add any additional context about the problem here. 
- [x] Root cause and the steps to reproduce. (If applicable): Try to install a Debian 12 Host with this Module 
- [x] Thought process behind the implementation.: i searched for the references of Debian and added the Cases for Debian 12. Afterwards i tried running Puppet with the forked Module on a Debian 12 Server and worked. 

## Related Issues (if any)
-

## Checklist
- [x] 🟢 Spec tests.: i ran the unit Tests and they finished without any failtures :) 
- [ ] 🟢 Acceptance tests.: i couldnt manage to get the acceptance Tests running on my System yet (not because of the Changes, but because of my System)
- [x] Manually verified. (For example `puppet apply`)

### CODE REVIEW

**Comment by TheMeier** [comment]
Well the spec tests  are not run for debian-12 though in part because of this: https://github.com/voxpupuli/facterdb/pull/283


https://github.com/puppetlabs/puppetlabs-apache/actions/runs/5751569702/job/15591026007?pr=2439#step:6:1 < - no debian-12 here

**Comment by Ramesh7** [comment]
> Well the spec tests are not run for debian-12 though in part because of this: [voxpupuli/facterdb#283](https://github.com/voxpupuli/facterdb/pull/283)
> 
> https://github.com/puppetlabs/puppetlabs-apache/actions/runs/5751569702/job/15591026007?pr=2439#step:6:1 < - no debian-12 here

@TheMeier that's because the puppet officially not supporting Debian 12, thats where its underlining tools haven't included into spec test coverage. 
Even though this PR gets merge, the Puppet official doesn't recommend for Debian 12 but you still can go unofficially.

**Comment by Ramesh7** [comment]
Updating label as `experimental` just let other know that Debian 12 is not yet official

**Comment by Ramesh7** [comment]
Taking this PR forward so that once we get hardware available for Debian12 we will get pipeline started running. Right now we do not have official support so do not recommend this to run with Debian 12 officially.

**Pull request merged**
