### PR TITLE
proxy: remove workaround for old broken clients

### PR DESCRIPTION
**Pull request by igalic**
this has been fixed for a long time
(https://bz.apache.org/bugzilla/show_bug.cgi?id=38864) and the
workaround documented by @niq http://www.apachetutor.org/admin/reverseproxies
hasn't been necessary for a long time.

### CODE REVIEW

**Comment by igalic** [comment]
i'm impressed how this actually passes tests.

since i haven't touched spec/ at all.

oh well, i guess that's probably because there's no spec tests exercising this code-path at all…

@DavidS you got any opinions to spare?

**Comment by DavidS** [comment]
https://github.com/puppetlabs/puppetlabs-apache/blob/master/spec/acceptance/vhost_spec.rb#L95 has some tests for this functionality, but the tests don't seem to be very inquisitive.

**Comment by igalic** [comment]
works for me™
do you want me to add anything?

**Comment by DavidS** [comment]
If you have time, it'd be great to have a test that actually talks through the proxy, otherwise just merge this.

**Comment by igalic** [comment]
time is an extremely valuable resource.
i have had those tests in spec/acceptance.
it was axed.

**Comment by tphoney** [comment]
Turns out the tests dont pass :(

**Comment by igalic** [comment]
which ones?

**Comment by tphoney** [comment]
@igalic i have a fix that i am testing, i will post it when ready. 
/spec/acceptance/vhost_spec.rb is failing on multiple OSes  in templates/vhost/_proxy.erb
we need a path associated with ProxyPassReverse 

 ProxyPassMatch /foo http://backend-foo/
  ProxyPassReverse http://backend-foo/
should become
 ProxyPassMatch /foo http://backend-foo/
  ProxyPassReverse /foo http://backend-foo/

**Comment by tphoney** [comment]
@igalic @DavidS my proposed fix #1327

**Pull request merged**
