### PR TITLE
mod_passenger: Allow setting PassengerSpawnMethod

### PR DESCRIPTION
**Pull request by wubr**

### CODE REVIEW

**Comment by igalic** [comment]
@wubr this will need documentation and perhaps some mild validation to catch the most erregious of errors

**Comment by wubr** [comment]
Good call.  How do the new commits look?

**Comment by igalic** [comment]
nice, @wubr!
would you mind squashing down those commits a bit?

**Comment by wubr** [comment]
Squashed.  Thanks for bearing with me!

**Comment by igalic** [comment]
thanks a lot @wubr

**Pull request merged**
