### PR TITLE
Modules-4500 Add optional "AdvertiseFrequency" directive in cluster.conf template

### PR DESCRIPTION
**Pull request by EmersonPrado**
If calling class defines `advertise_frequency`, and `server_advertise` is `true`, this change adds the directive `AdvertiseFrequency` in mod_cluster virtual host conf file template

### CODE REVIEW

**Comment by tphoney** [comment]
Looks like a good change, it might be worth documenting this new parameter in the readme.

**Comment by EmersonPrado** [comment]
@tphoney Good idea. Done.

**Comment by tphoney** [comment]
in the docs you say the default value is 10, but it in code it is undef. its late here, so i might be code blind

**Comment by wilson208** [comment]
@tphoney have looked at the docs [here](https://docs.jboss.org/mod_cluster/1.2.0/html_single/#d0e701) and AdvertiseFrequency defaults to 10ms when not defined. This PR only sets the AdvertiseFrequency in the template when the param is defined, therefore it defaults to 10ms when not defined.

This LGTM 👍

**Comment by EmersonPrado** [comment]
@wilson208 and @tphoney : would it be overkill to push a new commit improving the README to explain the default is from Apache modcluster, not from the Puppet class?
(Just for pickiness: 10s, not 10ms)

**Pull request merged**
