### PR TITLE
Added option to disable indexes globally.

### PR DESCRIPTION
**Pull request by tthayer**
This adds "Options -Indexes" to the base apache configuration file, which will disable indexes on directories that don't explicitly have "Options Indexes" set.

### CODE REVIEW

**Comment by tthayer** [comment]
I'm not seeing where the conflicts are and github isn't helping.

**Comment by igalic** [comment]
i think this makes for a bad name, or option, in general.

in my opinion this should be an `option` parameter which takes a string or an array of options.

**Comment by tthayer** [comment]
That is a good point. This is the only use case I've seen using the Option outside of a directory definition so I hadn't considered that use case.

**Comment by hunner** [comment]
The conflicts should become apparent if you do a rebase onto the current master.

**Comment by tthayer** [comment]
OK, rebased and updated now.

**Comment by tthayer** [comment]
And lost my changes. Time to read about how to git again.

**Comment by igalic** [comment]
here's a nice rundown of git by @eevee: http://eev.ee/blog/2015/04/24/just-enough-git-to-be-less-dangerous/

**Pull request closed without merging**
