### PR TITLE
add support for fcgi

### PR DESCRIPTION
**Pull request by mlhess**
This adds simple support for enabling the fcgi module.

### CODE REVIEW

**Comment by igalic** [comment]
that seems sensible.

**Comment by hunner** [comment]
@mlhess Could you please document this at https://github.com/puppetlabs/puppetlabs-apache#classes-apachemodmodule-name ? Thanks!

**Comment by igalic** [comment]
i'm also rerunning the trusty build
maybe it will somehow magically succeed now

**Comment by tphoney** [comment]
apologies, accidental close.

**Pull request merged**
