### PR TITLE
Add an option to configure PassengerLogFile

### PR DESCRIPTION
**Pull request by igalic**
PassengerLogFile (available since 5.0.5) allows us to configure a
separate file where (all) applications running under passenger will send
their stdout/stderr to.

This is helpful in reducing noise when trying to parse httpd's error log

### CODE REVIEW

**Comment by DavidS** [comment]
Hi!!

please add a note to README.passenger.md for this.

Cheers, David

**Comment by igalic** [comment]
hi @DavidS,

the mod_passenger documentation in README.passenger.md seems to be more outdated than the one in README.md… maybe we should just delete the former, and update the latter?

**Comment by DavidS** [comment]
@igalic, you are definitely more qualified to judge that than me.

**Comment by ekohl** [comment]
:+1: looks good.

**Comment by HelenCampbell** [comment]
Thanks @igalic !

**Pull request merged**
