### PR TITLE
Support itk on redhat

### PR DESCRIPTION
**Pull request by edestecd**

### CODE REVIEW

**Comment by edestecd** [comment]
I need to fix the spec test that expect unsupported os...

Does anyone have any feedback on my approach?
You probably want this pull against master?

**Comment by igalic** [comment]
@edestecd why is this a patch against 1.5.x?

**Comment by edestecd** [comment]
@igalic i'm being lazy.  That's the version I am currently stuck at ;)

**Comment by bmjen** [comment]
@edestecd Can you resubmit this fix against master? I'm going to close this PR, as we likely will not do another release from the 1.5.x branch.

**Pull request closed without merging**
