### PR TITLE
$apache::serveradmin parameter is unused

### PR DESCRIPTION
**Pull request by raybellis**

### CODE REVIEW

**Comment by david22swan** [comment]
@raybellis Unsure if this is needed, was under the impressions that `serveradmin` is supposed to be passed through to _file_header.rb and set there?

**Review by ekohl — CHANGES_REQUESTED** [review]
And to make sure it's clear there has been a review.

**Comment by david22swan** [comment]
@raybellis Any chance of you coming back to this?

**Comment by raybellis** [comment]
@david22swan I don't have the infrastructure to set up a test for this, but the patch is still relevant.   (for some reason I didn't get notifications from GitHub about your messages)

**Comment by david22swan** [comment]
Not sure what you mean by infrastructure, by adding testing I was referring to the addition of a small test such as this:
https://github.com/puppetlabs/puppetlabs-apache/blob/main/spec/acceptance/apache_parameters_spec.rb#L323
Something to show that the parameter compiles correctly and does what is intended.

**Comment by david22swan** [comment]
@raybellis ^^

**Pull request closed without merging**
