### PR TITLE
Added WSGI Options WSGIApplicationGroup and WSGIPythonOptimize

### PR DESCRIPTION
**Pull request by emetriqLikedeeler**
Added two "per server" WSGI Options
* WSGIApplicationGroup
* WSGIPythonOptimize

including tests and little documentation in README.md

In addition two small cosmetic changes:
* some spaces
* a little header for the vhost wsgi configuration block

### CODE REVIEW

**Comment by david22swan** [comment]
@emetriqLikedeeler Apologies but your PR failed the adhoc run on Debian 9. However it look's like it may be an issue that was since fixed as such if you could rebase your changes I would be happy to rerun the test's.

**Comment by david22swan** [comment]
screen shot 2019-02-06 at 10 41 53 am

**Comment by david22swan** [comment]
@emetriqLikedeeler Passed through the adhoc so I'm happy to merge.
Thanks for putting the work in :)

**Comment by emetriqChris** [comment]
Cool :-) Thanks!

**Pull request merged**
