### PR TITLE
Add vhost_default to apache::vhosts

### PR DESCRIPTION
**Pull request by AlessandroLorenzi**
just a little improvment but (imho) useful!

### CODE REVIEW

**Comment by eputnam** [comment]
@AlessandroLorenzi if this is something you're still interested in, could you talk about the use case for this change?

**Comment by AlessandroLorenzi** [comment]
You can have serveral vhosts with common parameters. In hiera you can split redoundant configurations in apache::vhosts::vhost_defaults and the list of vhosts in apache::vhosts::vhosts.

**Comment by david22swan** [comment]
@AlessandroLorenzi Is there any movement on this PR?

**Comment by david22swan** [comment]
@AlessandroLorenzi apologies, but due to the lack of movement on this PR I will be closing it. If however you later find the time to return to and complete it we will be more than happy to review and merge it.

**Pull request closed without merging**
