### PR TITLE
(MODULES-5990) - Managing conf_enabled

### PR DESCRIPTION
**Pull request by david22swan**

### CODE REVIEW

**Comment by david22swan** [comment]
Need's Tests

**Comment by pmcmaw** [comment]
Changed to a bug fix, as this is fixing a feature that wasn't implemented correctly.

**Comment by david22swan** [comment]
screen shot 2019-01-16 at 11 19 07 am

**Comment by david22swan** [comment]
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/modules/view/linux/view/_adhoc/view/apache/job/forge-module_puppetlabs-apache_init-manual-parameters_adhoc/74/

**Pull request merged**
