### PR TITLE
mod_auth_gssapi: Add support for every configuration directive

### PR DESCRIPTION
**Pull request by canth1**
This allows every configuration directive available to mod_auth_gssapi to be configured inside a directory section of a vhost.

Example

```puppet
include apache::mod::auth_gssapi
apache::vhost { 'sample.example.net':
  docroot     => '/path/to/directory',
  directories => [
    { path   => '/path/to/different/dir',
      gssapi => {
        acceptor_name            => '{HOSTNAME}',
        allowed_mech             => ['krb5', 'iakerb', 'ntlmssp'],
        basic_auth               => true,
        basic_auth_mech          => ['krb5', 'iakerb', 'ntlmssp'],
        basic_ticket_timeout     => 300,
        connection_bound         => true,
        cred_store               => {
          ccache        => ['/path/to/directory'],
          client_keytab => ['/path/to/example.keytab'],
          keytab        => ['/path/to/example.keytab'],
        },
        deleg_ccache_dir         => '/path/to/directory',
        deleg_ccache_env_var     => 'KRB5CCNAME',
        deleg_ccache_perms       => {
          mode => '0600',
          uid  => 'example-user',
          gid  => 'example-group',
        },
        deleg_ccache_unique      => true,
        impersonate              => true,
         local_name              => true,
        name_attributes          => 'json',
        negotiate_once           => true,
        publish_errors           => true,
        publish_mech             => true,
        required_name_attributes =>	'auth-indicators=high',
        session_key              => 'file:/path/to/example.key',
        signal_persistent_auth   => true,
        ssl_only                 => true,
        use_s4u2_proxy           => true,
        use_sessions             => true,
      }
    },
  ],
}
```
The above config results in an Apache configuration of:

```config
<Directory /path/to/directory>
    # mod_auth_gssapi configuration
    GssapiAcceptorName {HOSTNAME}
    GssapiAllowedMech krb5
    GssapiAllowedMech iakerb
    GssapiAllowedMech ntlmssp
    GssapiBasicAuth On
    GssapiBasicAuthMech krb5
    GssapiBasicAuthMech iakerb
    GssapiBasicAuthMech ntlmssp
    GssapiBasicTicketTimeout 300
    GssapiConnectionBound On
    GssapiCredStore ccache:FILE:/path/to/directory
    GssapiCredStore client_keytab:/path/to/example.keytab
    GssapiCredStore keytab:/path/to/example.keytab
    GssapiDelegCcacheDir /path/to/directory
    GssapiDelegCcacheEnvVar KRB5CCNAME
    GssapiDelegCcachePerms mode:0600 uid:example-user gid:example-group
    GssapiDelegCcacheUnique On
    GssapiImpersonate On
    GssapiLocalName On
    GssapiNameAttributes json
    GssapiNegotiateOnce On
    GssapiPublishErrors On
    GssapiPublishMech On
    GssapiRequiredNameAttributes "auth-indicators=high"
    GssapiSessionKey file:/path/to/example.key
    GssapiSignalPersistentAuth On
    GssapiSSLonly On
    GssapiUseS4U2Proxy On
    GssapiUseSessions On
</Directory>
```

### CODE REVIEW

**Review by bastelfreak — DISMISSED** [review]

**Review by david22swan — CHANGES_REQUESTED** [review]
@canth1 Hey, sorry for the wait on review.
Anyway, while this look's like a great change and an excellent addition of functionality it is causing some unit test failures seeming to originate from the new acceptor_name value.
If you could get this solved I would be happy to merge, I've included an example of the error below:

```
Failures:

  1) apache::vhost os-independent items on oraclelinux-6-x86_64  set everything! is expected to compile into a catalogue without dependency cycles
     Failure/Error: acceptor_name            => '{HOSTNAME}',

     NameError:
       undefined local variable or method `acceptor_name' for #<RSpec::ExampleGroups::ApacheVhost::OsIndependentItems::OnOraclelinux6X8664::SetEverything:0x00005576c6b33570>
     # ./spec/defines/vhost_spec.rb:255:in `block (6 levels) in <top (required)>'
     # ./spec/defines/vhost_spec.rb:531:in `block (6 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.5.0/bin/rspec:23:in `load'
     # ./vendor/bundle/ruby/2.5.0/bin/rspec:23:in `<top (required)>'
     # ./vendor/bundle/ruby/2.5.0/bin/bundle:23:in `load'
     # ./vendor/bundle/ruby/2.5.0/bin/bundle:23:in `<main>'
```

**Comment by canth1** [comment]
Thanks for the update on this. I'll work on getting those issues fixed. As far as the other pull requests, I would argue that you should use this one as it is a complete implementation of every mod_auth_gssapi configuration option. From what I've seen, the other pull requests only add a few additional options, leaving the functionality incomplete.

**Comment by canth1** [comment]
Looking at this closer, is the issue that the { and } aren't escaped correctly in the vhost_spec.rb file?

https://github.com/puppetlabs/puppetlabs-apache/pull/2214/files#diff-e1ca2aff131effcf3317f6b0fb468368163f59c5cb4c9598f15729bfe288646aR976

**Comment by david22swan** [comment]
I don't think so, from the way the error is presented it seem's to come from where the acceptor_name is being set.

**Comment by david22swan** [comment]
Reading through the errorlogs see a lot of:
```
          undefined local variable or method `acceptor_name' for #<RSpec::ExampleGroups::ApacheVhost::OsIndependentItems::OnRedhat6X8664::SetEverything:0x00005576d5d9ed78>

```

**Comment by david22swan** [comment]
@canth1 Is this still something you plan to work on?

**Comment by canth1** [comment]
> @canth1 Is this still something you plan to work on?

I really do, but from everything I've looked at I can't figure out what's throwing that error. Is it possible that it's a false positive?

**Comment by david22swan** [comment]
@canth1 Took a look at your failure and found what was causing it, basically you need to put your test values in strings, they don't mock correctly if just passed in naked, i.e.:
```
'acceptor_name'            => '{HOSTNAME}',
```
Sorry it took me so long to remember the test limitation, but if you fix this and rebase then your pr to resolve the conflicts should be good to merge.

**Comment by canth1** [comment]
Ok, I've updated the vhost_spec.rb and the issue should be fixed. Let me know if you need anything else from me!

**Comment by david22swan** [comment]
@canth1 Just one more change sorry.
You need to resolve the conflicts with the main branch, basically some alterations where made to it following the creation of your branch that now conflict with your own changes.
So you need to either rebase your changes onto the main branch, or hit the Github Resolve conflicts button and go through them manually.
It shouldn't take long.

**Comment by canth1** [comment]
> @canth1 Just one more change sorry. You need to resolve the conflicts with the main branch, basically some alterations where made to it following the creation of your branch that now conflict with your own changes. So you need to either rebase your changes onto the main branch, or hit the Github Resolve conflicts button and go through them manually. It shouldn't take long.

Ok, I just fixed those conflicts.

**Review by david22swan — APPROVED** [review]
LGTM

**Comment by david22swan** [comment]
@canth1 Ok that's that then, sorry for asking for so many changes but it all looks good now so I'm gonna go ahead and merge.
Thanks for putting in the work :)

**Pull request merged**
