### PR TITLE
changed typo

### PR DESCRIPTION
**Pull request by rexcze**
After changing variable nss_port to port in manifest file I did not changed port variable on "VirtualHost" line. Fixed

### CODE REVIEW

**Comment by igalic** [comment]
how come this works in our tests?

**Comment by rexcze** [comment]
Maybe because there are no test for mod_nss?

**Comment by igalic** [comment]
oh, right… i even opened two bug on that: https://tickets.puppetlabs.com/browse/MODULES-2809 && https://tickets.puppetlabs.com/browse/MODULES-2808

**Comment by igalic** [comment]
thank you @rexcze!

**Pull request merged**
