### PR TITLE
MODULES-1968 - Update the template to warn if using deprecated options

### PR DESCRIPTION
**Pull request by mhaskel**

### CODE REVIEW

**Comment by roman-mueller** [comment]
Why were the tests removed and not changed to check for the warning?
Ugh, I spent 90% of the initial PR's time on figuring out how to add those tests and now they get ripped out.

**Comment by igalic** [comment]
@mhaskel do you wanna restore the tests?

**Comment by mhaskel** [comment]
@roman-mueller AFAIK rspec-puppet can't actually detect warnings :(

**Comment by Aethylred** [comment]
@roman-mueller @mhaskel rspec-puppet can't detect warnings, but it can detect notify

**Comment by igalic** [comment]
joy. ^ @DavidS ping

**Comment by DavidS** [comment]
You need this rspec-puppet PR (https://github.com/rodjek/rspec-puppet/pull/292) and then you can use this pattern (https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/spec/functions/type_spec.rb#L10-L13) without the puppetlabs_spec_helper mess.

**Pull request merged**
