### PR TITLE
add additional directories options for LDAP Auth

### PR DESCRIPTION
**Pull request by zivis**
* AuthLDAPURL as auth_ldap_url
* AUTHLDAPBindDN as auth_ldap_bind_dn
* AuthLDAPBindPassword as auth_ldap_bind_password

### CODE REVIEW

**Comment by hunner** [comment]
Thanks @zivis ! Could you also document these new directories values? There is a section in the readme for them.

**Comment by zivis** [comment]
I've updated the README and squashed the update of the documentation into the commit.
Thanks for the hint

**Comment by antaflos** [comment]
Oh, :+1: from me! Can you also add support for `AuthLDAPGroupAttribute` and `AuthLDAPGroupAttributeIsDN` while you're at it? That'd be awesome :)

**Comment by zivis** [comment]
I also added support for AuthLDAPGroupAttribute and AuthLDAPGroupAttributeIsDN.

additional question:
I would like to fail the compilation when "AuthBasicProvider ldap" is used but the class ::apache:mod:authnz_ldap is not in catalogue. Should i do this in this PR/Commit or should i open a new one?

**Comment by antaflos** [comment]
@zivis I think such a failsafe is a separate feature and would belong in a separate PR since it does not *really* pertain to the changes you introduced here.

**Comment by tphoney** [comment]
@sathieu thanks for the work, i agree with @antaflos the extra functionality you were suggesting, belongs in a separate PR.

**Comment by sathieu** [comment]
@tphoney you mean thanks @zivis?

**Comment by tphoney** [comment]
@zivis apologies, thanks for your work. 
@sathieu thanks anyway

**Pull request merged**
