### PR TITLE
(feat) - Make compatible with Amazon Linux 2

### PR DESCRIPTION
**Pull request by engshine**

### CODE REVIEW

**Comment by david22swan** [comment]
@engshine Is there any movement on this pr??

**Comment by engshine** [comment]
> @engshine Is there any movement on this pr??

Hi @david22swan (and @pmcmaw), apologies for the delay.
I've rebased from puppetlabs-apache/master.

Cheers

**Comment by david22swan** [comment]
@engshine I'm afraid there's a problem with how you have rebased. When we say we rebase we mean the git method of transplanting your changes onto a new location, while what you have done is simply merge the master into your branch.
It's an easy mistake to make and happen's rather often, but it can cause problems when merging it into the code as it pollutes the history of the module and makes it hard to track down changes if problems occur.
I hate to ask this but if you could copy your original changes onto a fresh branch it would be greatly appreciated.

**Comment by david22swan** [comment]
@engshine Apologies but is there still movement on this pr??

**Comment by david22swan** [comment]
@engshine In order to move thing's along I have retrieved your original commit, rebased it onto the current master, pushed it back up and created a new PR which you can find here:
https://github.com/puppetlabs/puppetlabs-apache/pull/1898
As such I will now be closing this PR.
Thank you for the work that you put in and apologies on the time it has taken to get it merged.

**Pull request closed without merging**
